package com.elicitsoftware.service;

/*-
 * ***LICENSE_START***
 * Elicit Survey
 * %%
 * Copyright (C) 2025 The Regents of the University of Michigan - Rogel Cancer Center
 * %%
 * PolyForm Noncommercial License 1.0.0
 * <https://polyformproject.org/licenses/noncommercial/1.0.0>
 * ***LICENSE_END***
 */

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.persistence.EntityManager;
import jakarta.persistence.Query;
import jakarta.transaction.Transactional;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.sql.Timestamp;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Imports respondent data from export files generated by {@link RespondentExportService}.
 * <p>
 * This service parses the custom Elicit export format and uses parameterized queries
 * to safely insert data, preventing SQL injection attacks.
 * <p>
 * <strong>Format: ELICIT_EXPORT_V1</strong>
 * <ul>
 *   <li>Lines starting with # are comments/metadata</li>
 *   <li>Data lines: tablename: field1|field2|field3|...</li>
 *   <li>Fields are pipe-delimited with escape sequences: \| \\ \n \r</li>
 * </ul>
 * <p>
 * All timestamps are expected in ISO-8601 format with timezone offset
 * (e.g., {@code 2026-03-13T20:50:38.106-04:00}).
 *
 * @see RespondentExportService
 */
@ApplicationScoped
public class RespondentImportService {

    /**
     * Default constructor for CDI.
     */
    public RespondentImportService() {
        // CDI managed bean
    }

    private static final String FORMAT_VERSION = "ELICIT_EXPORT_V1";

    @Inject
    EntityManager em;

    /**
     * Result of an import operation.
     */
    public static class ImportResult {
        private final boolean success;
        private final int recordsImported;
        private final List<String> errors;
        private final Map<String, Integer> counts;

        /**
         * Creates a new ImportResult.
         *
         * @param success whether the import succeeded
         * @param recordsImported number of records imported
         * @param errors list of error messages
         * @param counts breakdown of records by table
         */
        public ImportResult(boolean success, int recordsImported, List<String> errors, Map<String, Integer> counts) {
            this.success = success;
            this.recordsImported = recordsImported;
            this.errors = errors;
            this.counts = counts;
        }

        /**
         * Returns whether the import succeeded.
         *
         * @return true if import succeeded
         */
        public boolean isSuccess() {
            return success;
        }

        /**
         * Returns the number of records imported.
         *
         * @return number of records imported
         */
        public int getRecordsImported() {
            return recordsImported;
        }

        /**
         * Returns the list of error messages.
         *
         * @return list of error messages
         */
        public List<String> getErrors() {
            return errors;
        }

        /**
         * Returns the breakdown of records by table.
         *
         * @return breakdown of records by table
         */
        public Map<String, Integer> getCounts() {
            return counts;
        }
    }

    /**
     * Imports respondent data from an Elicit export file.
     * <p>
     * Uses parameterized queries to prevent SQL injection.
     *
     * @param inputStream the input stream containing the export file
     * @return ImportResult with success status, counts, and any errors
     */
    @Transactional
    public ImportResult importFromFile(InputStream inputStream) {
        List<String> errors = new ArrayList<>();
        Map<String, Integer> counts = new HashMap<>();
        counts.put("respondents", 0);
        counts.put("answers", 0);
        counts.put("dependents", 0);
        counts.put("subjects", 0);
        counts.put("messages", 0);
        counts.put("respondent_psa", 0);

        int lineNumber = 0;
        Long newRespondentId = null;
        List<Long> subjectIds = new ArrayList<>();  // Track subject IDs by index

        try (BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream, StandardCharsets.UTF_8))) {
            String line;
            boolean versionValidated = false;

            while ((line = reader.readLine()) != null) {
                lineNumber++;
                line = line.trim();

                // Skip empty lines
                if (line.isEmpty()) {
                    continue;
                }

                // Handle comments and validate format version
                if (line.startsWith("#")) {
                    if (line.contains(FORMAT_VERSION)) {
                        versionValidated = true;
                    }
                    continue;
                }

                // Require version validation before processing data
                if (!versionValidated) {
                    errors.add("Line " + lineNumber + ": File does not start with valid format header (expected # " + FORMAT_VERSION + ")");
                    return new ImportResult(false, 0, errors, counts);
                }

                // Parse data line: tablename: field1|field2|...
                int colonIndex = line.indexOf(':');
                if (colonIndex < 0) {
                    errors.add("Line " + lineNumber + ": Invalid format, missing colon separator");
                    continue;
                }

                String tableName = line.substring(0, colonIndex).trim().toLowerCase();
                String fieldData = line.substring(colonIndex + 1).trim();
                String[] fields = parseFields(fieldData);

                try {
                    switch (tableName) {
                        case "respondents":
                            newRespondentId = insertRespondent(fields);
                            counts.put("respondents", counts.get("respondents") + 1);
                            break;
                        case "answers":
                            if (newRespondentId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert answer before respondent");
                                continue;
                            }
                            insertAnswer(fields, newRespondentId);
                            counts.put("answers", counts.get("answers") + 1);
                            break;
                        case "dependents":
                            if (newRespondentId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert dependent before respondent");
                                continue;
                            }
                            insertDependent(fields, newRespondentId);
                            counts.put("dependents", counts.get("dependents") + 1);
                            break;
                        case "subjects":
                            if (newRespondentId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert subject before respondent");
                                continue;
                            }
                            Long subjectId = insertSubject(fields, newRespondentId);
                            // Store subject ID at the index specified in the first field
                            int subjectIndex = parseIntOrNull(fields[0]);
                            while (subjectIds.size() <= subjectIndex) {
                                subjectIds.add(null);
                            }
                            subjectIds.set(subjectIndex, subjectId);
                            counts.put("subjects", counts.get("subjects") + 1);
                            break;
                        case "messages":
                            int msgSubjectIndex = parseIntOrNull(fields[0]);
                            if (msgSubjectIndex < 0 || msgSubjectIndex >= subjectIds.size() || subjectIds.get(msgSubjectIndex) == null) {
                                errors.add("Line " + lineNumber + ": Invalid subject index for message: " + msgSubjectIndex);
                                continue;
                            }
                            insertMessage(fields, subjectIds.get(msgSubjectIndex));
                            counts.put("messages", counts.get("messages") + 1);
                            break;
                        case "respondent_psa":
                            if (newRespondentId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert PSA before respondent");
                                continue;
                            }
                            insertRespondentPsa(fields, newRespondentId);
                            counts.put("respondent_psa", counts.get("respondent_psa") + 1);
                            break;
                        default:
                            errors.add("Line " + lineNumber + ": Unknown table: " + tableName);
                    }
                } catch (Exception e) {
                    errors.add("Line " + lineNumber + ": " + e.getMessage());
                    throw new RuntimeException("Import failed at line " + lineNumber + ": " + e.getMessage(), e);
                }
            }

            if (!versionValidated) {
                errors.add("File does not contain valid format header");
                return new ImportResult(false, 0, errors, counts);
            }

            int total = counts.values().stream().mapToInt(Integer::intValue).sum();
            return new ImportResult(errors.isEmpty(), total, errors, counts);

        } catch (IOException e) {
            errors.add("Failed to read file: " + e.getMessage());
            return new ImportResult(false, 0, errors, counts);
        }
    }

    /**
     * Parse pipe-delimited fields with escape sequence handling.
     */
    private String[] parseFields(String data) {
        List<String> fields = new ArrayList<>();
        StringBuilder current = new StringBuilder();
        boolean escaped = false;

        for (int i = 0; i < data.length(); i++) {
            char c = data.charAt(i);

            if (escaped) {
                switch (c) {
                    case '|' -> current.append('|');
                    case '\\' -> current.append('\\');
                    case 'n' -> current.append('\n');
                    case 'r' -> current.append('\r');
                    default -> {
                        current.append('\\');
                        current.append(c);
                    }
                }
                escaped = false;
            } else if (c == '\\') {
                escaped = true;
            } else if (c == '|') {
                fields.add(current.toString());
                current = new StringBuilder();
            } else {
                current.append(c);
            }
        }
        fields.add(current.toString());

        return fields.toArray(new String[0]);
    }

    private Long insertRespondent(String[] fields) {
        // Fields: survey_id, token, logins, created_dt, first_access_dt
        if (fields.length < 5) {
            throw new IllegalArgumentException("Respondent requires 5 fields, got " + fields.length);
        }

        Query seqQuery = em.createNativeQuery("SELECT nextval('survey.respondents_seq')");
        Long newId = ((Number) seqQuery.getSingleResult()).longValue();

        Query query = em.createNativeQuery("""
            INSERT INTO survey.respondents (id, survey_id, token, active, logins, created_dt, first_access_dt, finalized_dt)
            VALUES (?1, ?2, ?3, true, ?4, ?5, ?6, NULL)
            """);
        query.setParameter(1, newId);
        query.setParameter(2, parseIntOrNull(fields[0]));
        query.setParameter(3, nullIfEmpty(fields[1]));
        query.setParameter(4, parseIntOrNull(fields[2]));
        query.setParameter(5, parseTimestamp(fields[3]));
        query.setParameter(6, parseTimestamp(fields[4]));
        query.executeUpdate();

        return newId;
    }

    private void insertAnswer(String[] fields, Long respondentId) {
        // Fields: survey_id, step, step_instance, section, section_instance, question_display_order,
        //         question_instance, section_question_id, question_id, display_key, display_text,
        //         text_value, deleted, created_dt, saved_dt
        if (fields.length < 15) {
            throw new IllegalArgumentException("Answer requires 15 fields, got " + fields.length);
        }

        Query query = em.createNativeQuery("""
            INSERT INTO survey.answers (id, survey_id, respondent_id, step, step_instance, section, section_instance,
                question_display_order, question_instance, section_question_id, question_id,
                display_key, display_text, text_value, deleted, created_dt, saved_dt)
            VALUES (nextval('survey.answers_seq'), ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16)
            """);
        query.setParameter(1, parseIntOrNull(fields[0]));
        query.setParameter(2, respondentId);
        query.setParameter(3, parseIntOrNull(fields[1]));
        query.setParameter(4, parseIntOrNull(fields[2]));
        query.setParameter(5, parseIntOrNull(fields[3]));
        query.setParameter(6, parseIntOrNull(fields[4]));
        query.setParameter(7, parseIntOrNull(fields[5]));
        query.setParameter(8, parseIntOrNull(fields[6]));
        query.setParameter(9, parseLongOrNull(fields[7]));
        query.setParameter(10, parseLongOrNull(fields[8]));
        query.setParameter(11, nullIfEmpty(fields[9]));
        query.setParameter(12, nullIfEmpty(fields[10]));
        query.setParameter(13, nullIfEmpty(fields[11]));
        query.setParameter(14, parseBooleanOrNull(fields[12]));
        query.setParameter(15, parseTimestamp(fields[13]));
        query.setParameter(16, parseTimestamp(fields[14]));
        query.executeUpdate();
    }

    private void insertDependent(String[] fields, Long respondentId) {
        // Fields: upstream_display_key, downstream_display_key, relationship_id, deleted
        if (fields.length < 4) {
            throw new IllegalArgumentException("Dependent requires 4 fields, got " + fields.length);
        }

        String upstreamKey = nullIfEmpty(fields[0]);
        String downstreamKey = nullIfEmpty(fields[1]);

        // Look up answer IDs by display_key
        Query upstreamQuery = em.createNativeQuery(
                "SELECT id FROM survey.answers WHERE respondent_id = ?1 AND display_key = ?2");
        upstreamQuery.setParameter(1, respondentId);
        upstreamQuery.setParameter(2, upstreamKey);
        Long upstreamId = getLongResult(upstreamQuery);

        Query downstreamQuery = em.createNativeQuery(
                "SELECT id FROM survey.answers WHERE respondent_id = ?1 AND display_key = ?2");
        downstreamQuery.setParameter(1, respondentId);
        downstreamQuery.setParameter(2, downstreamKey);
        Long downstreamId = getLongResult(downstreamQuery);

        Query query = em.createNativeQuery("""
            INSERT INTO survey.dependents (id, respondent_id, upstream_id, downstream_id, relationship_id, deleted)
            VALUES (nextval('survey.dependents_seq'), ?1, ?2, ?3, ?4, ?5)
            """);
        query.setParameter(1, respondentId);
        query.setParameter(2, upstreamId);
        query.setParameter(3, downstreamId);
        query.setParameter(4, parseLongOrNull(fields[2]));
        query.setParameter(5, parseBooleanOrNull(fields[3]));
        query.executeUpdate();
    }

    private Long insertSubject(String[] fields, Long respondentId) {
        // Fields: subject_index, xid, firstname, lastname, middlename, dob, email, phone, department_id, survey_id, created_dt
        if (fields.length < 11) {
            throw new IllegalArgumentException("Subject requires 11 fields, got " + fields.length);
        }

        Query seqQuery = em.createNativeQuery("SELECT nextval('survey.subjects_seq')");
        Long newId = ((Number) seqQuery.getSingleResult()).longValue();

        Query query = em.createNativeQuery("""
            INSERT INTO survey.subjects (id, xid, firstname, lastname, middlename, dob, email, phone, department_id, survey_id, respondent_id, created_dt)
            VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12)
            """);
        query.setParameter(1, newId);
        query.setParameter(2, nullIfEmpty(fields[1]));
        query.setParameter(3, nullIfEmpty(fields[2]));
        query.setParameter(4, nullIfEmpty(fields[3]));
        query.setParameter(5, nullIfEmpty(fields[4]));
        query.setParameter(6, parseDate(fields[5]));
        query.setParameter(7, nullIfEmpty(fields[6]));
        query.setParameter(8, nullIfEmpty(fields[7]));
        query.setParameter(9, parseLongOrNull(fields[8]));
        query.setParameter(10, parseLongOrNull(fields[9]));
        query.setParameter(11, respondentId);
        query.setParameter(12, parseTimestamp(fields[10]));
        query.executeUpdate();

        return newId;
    }

    private void insertMessage(String[] fields, Long subjectId) {
        // Fields: subject_index, message_type, mime_type, subjectline, body, created_dt, sent_dt
        if (fields.length < 7) {
            throw new IllegalArgumentException("Message requires 7 fields, got " + fields.length);
        }

        Query query = em.createNativeQuery("""
            INSERT INTO survey.messages (id, subject_id, message_type, mime_type, subjectline, body, created_dt, sent_dt)
            VALUES (nextval('survey.messages_seq'), ?1, ?2, ?3, ?4, ?5, ?6, ?7)
            """);
        query.setParameter(1, subjectId);
        query.setParameter(2, parseIntOrNull(fields[1]));
        query.setParameter(3, nullIfEmpty(fields[2]));
        query.setParameter(4, nullIfEmpty(fields[3]));
        query.setParameter(5, nullIfEmpty(fields[4]));
        query.setParameter(6, parseTimestamp(fields[5]));
        query.setParameter(7, parseTimestamp(fields[6]));
        query.executeUpdate();
    }

    private void insertRespondentPsa(String[] fields, Long respondentId) {
        // Fields: post_survey_action_id, tries, status, error_msg, created_dt, uploaded_dt
        if (fields.length < 6) {
            throw new IllegalArgumentException("Respondent PSA requires 6 fields, got " + fields.length);
        }

        Query query = em.createNativeQuery("""
            INSERT INTO survey.respondent_psa (id, respondent_id, post_survey_action_id, tries, status, error_msg, created_dt, uploaded_dt)
            VALUES (nextval('survey.respondent_psa_seq'), ?1, ?2, ?3, ?4, ?5, ?6, ?7)
            """);
        query.setParameter(1, respondentId);
        query.setParameter(2, parseLongOrNull(fields[0]));
        query.setParameter(3, parseIntOrNull(fields[1]));
        query.setParameter(4, nullIfEmpty(fields[2]));
        query.setParameter(5, nullIfEmpty(fields[3]));
        query.setParameter(6, parseTimestamp(fields[4]));
        query.setParameter(7, parseTimestamp(fields[5]));
        query.executeUpdate();
    }

    // Helper methods for parsing field values

    private String nullIfEmpty(String value) {
        return (value == null || value.isEmpty()) ? null : value;
    }

    private Integer parseIntOrNull(String value) {
        if (value == null || value.isEmpty()) {
            return null;
        }
        try {
            return Integer.parseInt(value);
        } catch (NumberFormatException e) {
            return null;
        }
    }

    private Long parseLongOrNull(String value) {
        if (value == null || value.isEmpty()) {
            return null;
        }
        try {
            return Long.parseLong(value);
        } catch (NumberFormatException e) {
            return null;
        }
    }

    private Boolean parseBooleanOrNull(String value) {
        if (value == null || value.isEmpty()) {
            return null;
        }
        return Boolean.parseBoolean(value) || "t".equalsIgnoreCase(value);
    }

    /**
     * Parses an ISO-8601 timestamp string to a SQL Timestamp.
     * <p>
     * Expects format with timezone offset (e.g., {@code 2026-03-13T20:50:38.106-04:00}).
     *
     * @param value timestamp string in ISO-8601 format, or null/empty
     * @return SQL Timestamp, or null if input is null/empty
     */
    private Timestamp parseTimestamp(String value) {
        if (value == null || value.isEmpty()) {
            return null;
        }
        OffsetDateTime odt = OffsetDateTime.parse(value);
        return Timestamp.from(odt.toInstant());
    }

    private java.sql.Date parseDate(String value) {
        if (value == null || value.isEmpty()) {
            return null;
        }
        try {
            return java.sql.Date.valueOf(value);
        } catch (IllegalArgumentException e) {
            return null;
        }
    }

    private Long getLongResult(Query query) {
        try {
            Object result = query.getSingleResult();
            if (result instanceof Number) {
                return ((Number) result).longValue();
            }
            return null;
        } catch (Exception e) {
            return null;
        }
    }
}
