package com.elicitsoftware.service;

/*-
 * ***LICENSE_START***
 * Elicit Survey
 * %%
 * Copyright (C) 2025 The Regents of the University of Michigan - Rogel Cancer Center
 * %%
 * PolyForm Noncommercial License 1.0.0
 * <https://polyformproject.org/licenses/noncommercial/1.0.0>
 * ***LICENSE_END***
 */

import com.elicitsoftware.admin.upload.MultipartBody;
import jakarta.annotation.security.RolesAllowed;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;

/**
 * REST endpoint that imports respondent data from Elicit export files.
 * <p>
 * Accepts files generated by RespondentExportService and uses parameterized
 * queries to safely import respondent data.
 */
@Path("/secured/import")
@ApplicationScoped
public class RespondentImportResource {

    /**
     * Default constructor for CDI.
     */
    public RespondentImportResource() {
        // CDI managed bean
    }

    @Inject
    RespondentImportService respondentImportService;

    /**
     * Import respondent data from an Elicit export file.
     * <p>
     * The file should be one generated by the respondent export endpoint (.elicit format).
     * The import uses parameterized queries to prevent SQL injection.
     *
     * @param multipartBody the multipart form data containing the export file
     * @return JSON response with import results or error information
     */
    @POST
    @RolesAllowed("elicit_admin")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @Produces(MediaType.APPLICATION_JSON)
    public Response importRespondent(MultipartBody multipartBody) {
        if (multipartBody.file == null) {
            return Response.status(Response.Status.BAD_REQUEST)
                    .entity(new ImportResponse(false, 0, "No file provided in the 'file' field", null))
                    .build();
        }

        try {
            RespondentImportService.ImportResult result = respondentImportService.importFromFile(multipartBody.file);

            ImportResponse response = new ImportResponse(
                    result.isSuccess(),
                    result.getRecordsImported(),
                    result.isSuccess() ? "Import completed successfully" : String.join("; ", result.getErrors()),
                    result.getCounts()
            );

            if (result.isSuccess()) {
                return Response.ok(response).build();
            } else {
                return Response.status(Response.Status.BAD_REQUEST)
                        .entity(response)
                        .build();
            }

        } catch (Exception e) {
            ImportResponse response = new ImportResponse(false, 0, "Import failed: " + e.getMessage(), null);
            return Response.status(Response.Status.INTERNAL_SERVER_ERROR)
                    .entity(response)
                    .build();
        }
    }

    /**
     * Response DTO for import operations.
     */
    public static class ImportResponse {
        private boolean success;
        private int recordsImported;
        private String message;
        private java.util.Map<String, Integer> counts;

        /**
         * Default constructor for JSON deserialization.
         */
        public ImportResponse() {
            // JSON deserialization
        }

        /**
         * Creates a new ImportResponse.
         *
         * @param success whether the import succeeded
         * @param recordsImported number of records imported
         * @param message status or error message
         * @param counts breakdown of records by table
         */
        public ImportResponse(boolean success, int recordsImported, String message, java.util.Map<String, Integer> counts) {
            this.success = success;
            this.recordsImported = recordsImported;
            this.message = message;
            this.counts = counts;
        }

        /**
         * Returns whether the import succeeded.
         *
         * @return true if import succeeded
         */
        public boolean isSuccess() {
            return success;
        }

        /**
         * Sets whether the import succeeded.
         *
         * @param success whether import succeeded
         */
        public void setSuccess(boolean success) {
            this.success = success;
        }

        /**
         * Returns the number of records imported.
         *
         * @return number of records imported
         */
        public int getRecordsImported() {
            return recordsImported;
        }

        /**
         * Sets the number of records imported.
         *
         * @param recordsImported number of records imported
         */
        public void setRecordsImported(int recordsImported) {
            this.recordsImported = recordsImported;
        }

        /**
         * Returns the status or error message.
         *
         * @return status or error message
         */
        public String getMessage() {
            return message;
        }

        /**
         * Sets the status or error message.
         *
         * @param message status or error message
         */
        public void setMessage(String message) {
            this.message = message;
        }

        /**
         * Returns the breakdown of records by table.
         *
         * @return breakdown of records by table
         */
        public java.util.Map<String, Integer> getCounts() {
            return counts;
        }

        /**
         * Sets the breakdown of records by table.
         *
         * @param counts breakdown of records by table
         */
        public void setCounts(java.util.Map<String, Integer> counts) {
            this.counts = counts;
        }
    }
}
