package com.elicitsoftware.service;

/*-
 * ***LICENSE_START***
 * Elicit Survey
 * %%
 * Copyright (C) 2025 The Regents of the University of Michigan - Rogel Cancer Center
 * %%
 * PolyForm Noncommercial License 1.0.0
 * <https://polyformproject.org/licenses/noncommercial/1.0.0>
 * ***LICENSE_END***
 */

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.persistence.EntityManager;
import jakarta.persistence.Query;
import jakarta.transaction.Transactional;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Imports survey definition data from export files generated by {@link SurveyDefinitionExportService}.
 * <p>
 * This service parses the custom Elicit Survey export format and uses parameterized queries
 * to safely insert data, preventing SQL injection attacks.
 * <p>
 * <strong>Format: ELICIT_SURVEY_EXPORT_V1</strong>
 * <ul>
 *   <li>Lines starting with # are comments/metadata</li>
 *   <li>Data lines: tablename: source_id|field1|field2|...</li>
 *   <li>Fields are pipe-delimited with escape sequences: \| \\ \n \r</li>
 *   <li>The source_id (first field) is the original ID from the exporting system, used
 *       to resolve FK references; new IDs are allocated from sequences in this system.</li>
 * </ul>
 * <p>
 * <strong>ID generation strategy:</strong>
 * <ul>
 *   <li>surveys — explicit {@code nextval('survey.surveys_seq')}, captured as {@code newSurveyId}</li>
 *   <li>select_groups — explicit nextval, old→new stored in {@code selectGroupIdMap}</li>
 *   <li>select_items — inline nextval; group_id resolved via selectGroupIdMap</li>
 *   <li>steps — explicit nextval, old→new stored in {@code stepIdMap}</li>
 *   <li>sections — explicit nextval, old→new stored in {@code sectionIdMap}</li>
 *   <li>steps_sections — explicit nextval, old→new stored in {@code stepsSectionIdMap}</li>
 *   <li>questions — explicit nextval, old→new stored in {@code questionIdMap}</li>
 *   <li>sections_questions — explicit nextval, old→new stored in {@code sectionsQuestionIdMap}</li>
 *   <li>relationships — inline nextval; all FK refs resolved via maps</li>
 *   <li>reports — inline nextval</li>
 *   <li>post_survey_actions — inline nextval</li>
 *   <li>dimensions — explicit nextval or reuse existing row by name; stored in {@code dimensionIdMap}</li>
 *   <li>ontology — explicit nextval or reuse existing row by (name, tag); dimension resolved via dimensionIdMap; stored in {@code ontologyIdMap}</li>
 *   <li>metadata — inline nextval; FK refs resolved via maps</li>
 * </ul>
 * <p>
 * Static lookup table references (type_id, operator_id, action_id) are imported
 * verbatim — they must exist in the target system with the same IDs.
 * <p>
 * The entire import is wrapped in a single {@code @Transactional} method — any failure
 * rolls back all rows inserted in that call.
 *
 * @see SurveyDefinitionExportService
 */
@ApplicationScoped
public class SurveyDefinitionImportService {

    /**
     * Default constructor for CDI.
     */
    public SurveyDefinitionImportService() {
        // CDI managed bean
    }

    private static final String FORMAT_VERSION = SurveyDefinitionExportService.FORMAT_VERSION;

    @Inject
    EntityManager em;

    /**
     * Result of an import operation.
     */
    public static class ImportResult {
        private final boolean success;
        private final int recordsImported;
        private final List<String> errors;
        private final Map<String, Integer> counts;

        /**
         * Creates a new ImportResult.
         *
         * @param success whether the import succeeded
         * @param recordsImported number of records imported
         * @param errors list of error messages
         * @param counts breakdown of records by table
         */
        public ImportResult(boolean success, int recordsImported, List<String> errors, Map<String, Integer> counts) {
            this.success = success;
            this.recordsImported = recordsImported;
            this.errors = errors;
            this.counts = counts;
        }

        /**
         * Indicates whether the import succeeded.
         * @return true if import succeeded
         */
        public boolean isSuccess() { return success; }

        /**
         * Returns the number of records imported.
         * @return number of records imported
         */
        public int getRecordsImported() { return recordsImported; }

        /**
         * Returns the list of error messages from import.
         * @return list of error messages
         */
        public List<String> getErrors() { return errors; }

        /**
         * Returns the breakdown of records imported by table.
         * @return breakdown of records by table
         */
        public Map<String, Integer> getCounts() { return counts; }
    }

    /**
     * Imports survey definition data from an Elicit Survey export file.
     * <p>
     * Data lines must appear in dependency order as written by the exporter:
     * surveys → select_groups → select_items → steps → sections → steps_sections
     * → questions → sections_questions → relationships → reports → post_survey_actions
     * → dimensions → ontology → metadata
     * <p>
     * Uses parameterized queries to prevent SQL injection.
     *
     * @param inputStream the input stream containing the export file
     * @return ImportResult with success status, counts, and any errors
     */
    @Transactional
    public ImportResult importFromFile(InputStream inputStream) {
        List<String> errors = new ArrayList<>();
        Map<String, Integer> counts = new HashMap<>();
        counts.put("surveys", 0);
        counts.put("select_groups", 0);
        counts.put("select_items", 0);
        counts.put("steps", 0);
        counts.put("sections", 0);
        counts.put("steps_sections", 0);
        counts.put("questions", 0);
        counts.put("sections_questions", 0);
        counts.put("relationships", 0);
        counts.put("reports", 0);
        counts.put("post_survey_actions", 0);
        counts.put("dimensions", 0);
        counts.put("ontology", 0);
        counts.put("metadata", 0);

        // State: new survey ID and old→new ID maps for each entity type
        Long newSurveyId = null;
        Map<Long, Long> selectGroupIdMap = new HashMap<>();
        Map<Long, Long> stepIdMap = new HashMap<>();
        Map<Long, Long> sectionIdMap = new HashMap<>();
        Map<Long, Long> stepsSectionIdMap = new HashMap<>();
        Map<Long, Long> questionIdMap = new HashMap<>();
        Map<Long, Long> sectionsQuestionIdMap = new HashMap<>();
        Map<Long, Long> dimensionIdMap = new HashMap<>();
        Map<Long, Long> ontologyIdMap = new HashMap<>();

        int lineNumber = 0;

        try (BufferedReader reader = new BufferedReader(
                new InputStreamReader(inputStream, StandardCharsets.UTF_8))) {
            String line;
            boolean versionValidated = false;

            while ((line = reader.readLine()) != null) {
                lineNumber++;
                line = line.trim();

                if (line.isEmpty()) {
                    continue;
                }

                if (line.startsWith("#")) {
                    if (line.contains(FORMAT_VERSION)) {
                        versionValidated = true;
                    }
                    continue;
                }

                if (!versionValidated) {
                    errors.add("Line " + lineNumber + ": File does not start with valid format header (expected # "
                            + FORMAT_VERSION + ")");
                    return new ImportResult(false, 0, errors, counts);
                }

                // Data line: "tablename: field1|field2|..."
                int colonIndex = line.indexOf(':');
                if (colonIndex < 0) {
                    errors.add("Line " + lineNumber + ": Invalid format, missing colon separator");
                    continue;
                }

                String tableName = line.substring(0, colonIndex).trim().toLowerCase();
                String fieldData = line.substring(colonIndex + 1).trim();
                String[] fields = parseFields(fieldData);

                try {
                    switch (tableName) {
                        case "surveys": {
                            if (newSurveyId != null) {
                                errors.add("Line " + lineNumber + ": Multiple survey records found; only one supported per file");
                                continue;
                            }
                            newSurveyId = insertSurvey(fields);
                            counts.merge("surveys", 1, Integer::sum);
                            break;
                        }
                        case "select_groups": {
                            if (newSurveyId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert select_group before survey");
                                continue;
                            }
                            Long sourceId = parseLongOrNull(fields[0]);
                            Long newId = insertSelectGroup(fields, newSurveyId);
                            selectGroupIdMap.put(sourceId, newId);
                            counts.merge("select_groups", 1, Integer::sum);
                            break;
                        }
                        case "select_items": {
                            if (newSurveyId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert select_item before survey");
                                continue;
                            }
                            insertSelectItem(fields, newSurveyId, selectGroupIdMap);
                            counts.merge("select_items", 1, Integer::sum);
                            break;
                        }
                        case "steps": {
                            if (newSurveyId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert step before survey");
                                continue;
                            }
                            Long sourceId = parseLongOrNull(fields[0]);
                            Long newId = insertStep(fields, newSurveyId);
                            stepIdMap.put(sourceId, newId);
                            counts.merge("steps", 1, Integer::sum);
                            break;
                        }
                        case "sections": {
                            if (newSurveyId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert section before survey");
                                continue;
                            }
                            Long sourceId = parseLongOrNull(fields[0]);
                            Long newId = insertSection(fields, newSurveyId);
                            sectionIdMap.put(sourceId, newId);
                            counts.merge("sections", 1, Integer::sum);
                            break;
                        }
                        case "steps_sections": {
                            if (newSurveyId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert steps_section before survey");
                                continue;
                            }
                            Long sourceId = parseLongOrNull(fields[0]);
                            Long newId = insertStepsSection(fields, newSurveyId, stepIdMap, sectionIdMap);
                            stepsSectionIdMap.put(sourceId, newId);
                            counts.merge("steps_sections", 1, Integer::sum);
                            break;
                        }
                        case "questions": {
                            if (newSurveyId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert question before survey");
                                continue;
                            }
                            Long sourceId = parseLongOrNull(fields[0]);
                            Long newId = insertQuestion(fields, newSurveyId, selectGroupIdMap);
                            questionIdMap.put(sourceId, newId);
                            counts.merge("questions", 1, Integer::sum);
                            break;
                        }
                        case "sections_questions": {
                            if (newSurveyId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert sections_question before survey");
                                continue;
                            }
                            Long sourceId = parseLongOrNull(fields[0]);
                            Long newId = insertSectionsQuestion(fields, newSurveyId, questionIdMap, sectionIdMap);
                            sectionsQuestionIdMap.put(sourceId, newId);
                            counts.merge("sections_questions", 1, Integer::sum);
                            break;
                        }
                        case "relationships": {
                            if (newSurveyId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert relationship before survey");
                                continue;
                            }
                            insertRelationship(fields, newSurveyId, stepIdMap, sectionsQuestionIdMap, stepsSectionIdMap);
                            counts.merge("relationships", 1, Integer::sum);
                            break;
                        }
                        case "reports": {
                            if (newSurveyId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert report before survey");
                                continue;
                            }
                            insertReport(fields, newSurveyId);
                            counts.merge("reports", 1, Integer::sum);
                            break;
                        }
                        case "post_survey_actions": {
                            if (newSurveyId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert post_survey_action before survey");
                                continue;
                            }
                            insertPostSurveyAction(fields, newSurveyId);
                            counts.merge("post_survey_actions", 1, Integer::sum);
                            break;
                        }
                        case "dimensions": {
                            Long sourceId = parseLongOrNull(fields[0]);
                            Long newId = insertOrReuseDimension(fields);
                            dimensionIdMap.put(sourceId, newId);
                            counts.merge("dimensions", 1, Integer::sum);
                            break;
                        }
                        case "ontology": {
                            if (newSurveyId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert ontology before survey");
                                continue;
                            }
                            Long sourceId = parseLongOrNull(fields[0]);
                            Long newId = insertOrReuseOntology(fields, newSurveyId, dimensionIdMap);
                            ontologyIdMap.put(sourceId, newId);
                            counts.merge("ontology", 1, Integer::sum);
                            break;
                        }
                        case "metadata": {
                            if (newSurveyId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert metadata before survey");
                                continue;
                            }
                            insertMetadata(fields, newSurveyId, stepsSectionIdMap, questionIdMap,
                                    sectionsQuestionIdMap, ontologyIdMap);
                            counts.merge("metadata", 1, Integer::sum);
                            break;
                        }
                        default:
                            errors.add("Line " + lineNumber + ": Unknown table: " + tableName);
                    }
                } catch (Exception e) {
                    errors.add("Line " + lineNumber + ": " + e.getMessage());
                    throw new RuntimeException("Import failed at line " + lineNumber + ": " + e.getMessage(), e);
                }
            }

            if (!versionValidated) {
                errors.add("File does not contain valid format header");
                return new ImportResult(false, 0, errors, counts);
            }

            int total = counts.values().stream().mapToInt(Integer::intValue).sum();
            return new ImportResult(errors.isEmpty(), total, errors, counts);

        } catch (IOException e) {
            errors.add("Failed to read file: " + e.getMessage());
            return new ImportResult(false, 0, errors, counts);
        }
    }

    // -------------------------------------------------------------------------
    // Insert methods
    // -------------------------------------------------------------------------

    /**
     * Inserts a new survey row using a fresh sequence ID.
     * Fields: source_id|name|display_order|title|description|initial_display_key|post_survey_url
     * <p>
     * Note: display_order is computed as MAX(display_order) + 1 to avoid conflicts,
     * rather than using the value from the export file.
     */
    private Long insertSurvey(String[] fields) {
        if (fields.length < 7) {
            throw new IllegalArgumentException("surveys requires 7 fields, got " + fields.length);
        }
        Query seqQuery = em.createNativeQuery("SELECT nextval('survey.surveys_seq')");
        Long newId = ((Number) seqQuery.getSingleResult()).longValue();

        // Compute next display_order as max + 1 to avoid unique constraint violations
        Query maxOrderQuery = em.createNativeQuery(
                "SELECT COALESCE(MAX(display_order), 0) + 1 FROM survey.surveys");
        Integer nextDisplayOrder = ((Number) maxOrderQuery.getSingleResult()).intValue();

        Query query = em.createNativeQuery("""
                INSERT INTO survey.surveys
                    (id, name, display_order, title, description, initial_display_key, post_survey_url)
                VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
                """);
        query.setParameter(1, newId);
        query.setParameter(2, nullIfEmpty(fields[1]));
        query.setParameter(3, nextDisplayOrder);
        query.setParameter(4, nullIfEmpty(fields[3]));
        query.setParameter(5, nullIfEmpty(fields[4]));
        query.setParameter(6, nullIfEmpty(fields[5]));
        query.setParameter(7, nullIfEmpty(fields[6]));
        query.executeUpdate();
        return newId;
    }

    /**
     * Inserts a new select_group row.
     * Fields: source_id|name|description|data_type
     */
    private Long insertSelectGroup(String[] fields, Long surveyId) {
        if (fields.length < 4) {
            throw new IllegalArgumentException("select_groups requires 4 fields, got " + fields.length);
        }
        Query seqQuery = em.createNativeQuery("SELECT nextval('survey.select_groups_seq')");
        Long newId = ((Number) seqQuery.getSingleResult()).longValue();

        String dataType = nullIfEmpty(fields[3]);

        Query query = em.createNativeQuery("""
                INSERT INTO survey.select_groups (id, survey_id, name, description, data_type)
                VALUES (?1, ?2, ?3, ?4, ?5)
                """);
        query.setParameter(1, newId);
        query.setParameter(2, surveyId);
        query.setParameter(3, nullIfEmpty(fields[1]));
        query.setParameter(4, nullIfEmpty(fields[2]));
        query.setParameter(5, dataType != null ? dataType : "Text");
        query.executeUpdate();
        return newId;
    }

    /**
     * Inserts a new select_item row; group_id resolved via selectGroupIdMap.
     * Fields: source_id|group_id|display_text|display_order|coded_value
     */
    private void insertSelectItem(String[] fields, Long surveyId, Map<Long, Long> selectGroupIdMap) {
        if (fields.length < 5) {
            throw new IllegalArgumentException("select_items requires 5 fields, got " + fields.length);
        }
        Long oldGroupId = parseLongOrNull(fields[1]);
        Long newGroupId = resolveRequired(oldGroupId, selectGroupIdMap, "select_group (for select_item)");

        Query query = em.createNativeQuery("""
                INSERT INTO survey.select_items
                    (id, survey_id, group_id, display_text, display_order, coded_value)
                VALUES (nextval('survey.select_items_seq'), ?1, ?2, ?3, ?4, ?5)
                """);
        query.setParameter(1, surveyId);
        query.setParameter(2, newGroupId);
        query.setParameter(3, nullIfEmpty(fields[2]));
        query.setParameter(4, parseIntOrNull(fields[3]));
        query.setParameter(5, nullIfEmpty(fields[4]));
        query.executeUpdate();
    }

    /**
     * Inserts a new step row.
     * Fields: source_id|display_order|name|dimension_name|description
     */
    private Long insertStep(String[] fields, Long surveyId) {
        if (fields.length < 5) {
            throw new IllegalArgumentException("steps requires 5 fields, got " + fields.length);
        }
        Query seqQuery = em.createNativeQuery("SELECT nextval('survey.steps_seq')");
        Long newId = ((Number) seqQuery.getSingleResult()).longValue();

        Query query = em.createNativeQuery("""
                INSERT INTO survey.steps
                    (id, survey_id, display_order, name, dimension_name, description)
                VALUES (?1, ?2, ?3, ?4, ?5, ?6)
                """);
        query.setParameter(1, newId);
        query.setParameter(2, surveyId);
        query.setParameter(3, parseIntOrNull(fields[1]));
        query.setParameter(4, nullIfEmpty(fields[2]));
        query.setParameter(5, nullIfEmpty(fields[3]));
        query.setParameter(6, nullIfEmpty(fields[4]));
        query.executeUpdate();
        return newId;
    }

    /**
     * Inserts a new section row.
     * Fields: source_id|display_order|name|dimension_name|description
     * <p>
     * Note: If dimension_name is empty, it defaults to the section name to satisfy NOT NULL constraint.
     */
    private Long insertSection(String[] fields, Long surveyId) {
        if (fields.length < 5) {
            throw new IllegalArgumentException("sections requires 5 fields, got " + fields.length);
        }
        Query seqQuery = em.createNativeQuery("SELECT nextval('survey.sections_seq')");
        Long newId = ((Number) seqQuery.getSingleResult()).longValue();

        String name = nullIfEmpty(fields[2]);
        String dimensionName = nullIfEmpty(fields[3]);
        // Default dimension_name to section name if empty (NOT NULL constraint)
        if (dimensionName == null) {
            dimensionName = name != null ? name : "";
        }

        Query query = em.createNativeQuery("""
                INSERT INTO survey.sections
                    (id, survey_id, display_order, name, dimension_name, description)
                VALUES (?1, ?2, ?3, ?4, ?5, ?6)
                """);
        query.setParameter(1, newId);
        query.setParameter(2, surveyId);
        query.setParameter(3, parseIntOrNull(fields[1]));
        query.setParameter(4, name);
        query.setParameter(5, dimensionName);
        query.setParameter(6, nullIfEmpty(fields[4]));
        query.executeUpdate();
        return newId;
    }

    /**
     * Inserts a new steps_sections row; step_id and section_id resolved via maps.
     * Fields: source_id|step_id|step_display_order|section_id|section_display_order|display_key
     */
    private Long insertStepsSection(String[] fields, Long surveyId,
            Map<Long, Long> stepIdMap, Map<Long, Long> sectionIdMap) {
        if (fields.length < 6) {
            throw new IllegalArgumentException("steps_sections requires 6 fields, got " + fields.length);
        }
        Long newStepId = resolveRequired(parseLongOrNull(fields[1]), stepIdMap, "step (for steps_sections)");
        Long newSectionId = resolveRequired(parseLongOrNull(fields[3]), sectionIdMap, "section (for steps_sections)");

        Query seqQuery = em.createNativeQuery("SELECT nextval('survey.steps_sections_seq')");
        Long newId = ((Number) seqQuery.getSingleResult()).longValue();

        Query query = em.createNativeQuery("""
                INSERT INTO survey.steps_sections
                    (id, survey_id, step_id, step_display_order, section_id, section_display_order, display_key)
                VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
                """);
        query.setParameter(1, newId);
        query.setParameter(2, surveyId);
        query.setParameter(3, newStepId);
        query.setParameter(4, parseIntOrNull(fields[2]));
        query.setParameter(5, newSectionId);
        query.setParameter(6, parseIntOrNull(fields[4]));
        query.setParameter(7, nullIfEmpty(fields[5]));
        query.executeUpdate();
        return newId;
    }

    /**
     * Inserts a new question row; select_group_id resolved via selectGroupIdMap (nullable).
     * Fields: source_id|type_id|text|short_text|tool_tip|required|min_value|max_value|
     *         validation_text|select_group_id|mask|placeholder|default_value|variant
     */
    private Long insertQuestion(String[] fields, Long surveyId, Map<Long, Long> selectGroupIdMap) {
        if (fields.length < 14) {
            throw new IllegalArgumentException("questions requires 14 fields, got " + fields.length);
        }
        Long oldSelectGroupId = parseLongOrNull(fields[9]);
        Long newSelectGroupId = null;
        if (oldSelectGroupId != null) {
            newSelectGroupId = resolveRequired(oldSelectGroupId, selectGroupIdMap, "select_group (for question)");
        }

        Query seqQuery = em.createNativeQuery("SELECT nextval('survey.questions_seq')");
        Long newId = ((Number) seqQuery.getSingleResult()).longValue();

        Query query = em.createNativeQuery("""
                INSERT INTO survey.questions
                    (id, survey_id, type_id, text, short_text, tool_tip, required,
                     min_value, max_value, validation_text, select_group_id,
                     mask, placeholder, default_value, variant)
                VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15)
                """);
        query.setParameter(1, newId);
        query.setParameter(2, surveyId);
        query.setParameter(3, parseIntOrNull(fields[1]));               // type_id (static)
        query.setParameter(4, nullIfEmpty(fields[2]));                  // text
        query.setParameter(5, nullIfEmpty(fields[3]));                  // short_text
        query.setParameter(6, nullIfEmpty(fields[4]));                  // tool_tip
        query.setParameter(7, parseBooleanOrFalse(fields[5]));          // required
        query.setParameter(8, parseIntOrNull(fields[6]));               // min_value
        query.setParameter(9, parseIntOrNull(fields[7]));               // max_value
        query.setParameter(10, nullIfEmpty(fields[8]));                 // validation_text
        query.setParameter(11, newSelectGroupId);                       // select_group_id (resolved)
        query.setParameter(12, nullIfEmpty(fields[10]));                // mask
        query.setParameter(13, nullIfEmpty(fields[11]));                // placeholder
        query.setParameter(14, nullIfEmpty(fields[12]));                // default_value
        query.setParameter(15, nullIfEmpty(fields[13]));                // variant
        query.executeUpdate();
        return newId;
    }

    /**
     * Inserts a new sections_questions row; question_id and section_id resolved via maps.
     * Fields: source_id|question_id|section_id|display_order
     */
    private Long insertSectionsQuestion(String[] fields, Long surveyId,
            Map<Long, Long> questionIdMap, Map<Long, Long> sectionIdMap) {
        if (fields.length < 4) {
            throw new IllegalArgumentException("sections_questions requires 4 fields, got " + fields.length);
        }
        Long newQuestionId = resolveRequired(parseLongOrNull(fields[1]), questionIdMap, "question (for sections_questions)");
        Long newSectionId = resolveRequired(parseLongOrNull(fields[2]), sectionIdMap, "section (for sections_questions)");

        Query seqQuery = em.createNativeQuery("SELECT nextval('survey.sections_questions_seq')");
        Long newId = ((Number) seqQuery.getSingleResult()).longValue();

        Query query = em.createNativeQuery("""
                INSERT INTO survey.sections_questions
                    (id, survey_id, question_id, section_id, display_order)
                VALUES (?1, ?2, ?3, ?4, ?5)
                """);
        query.setParameter(1, newId);
        query.setParameter(2, surveyId);
        query.setParameter(3, newQuestionId);
        query.setParameter(4, newSectionId);
        query.setParameter(5, parseIntOrNull(fields[3]));
        query.executeUpdate();
        return newId;
    }

    /**
     * Inserts a new relationship row; all FK refs resolved via maps. Nullable FKs become null
     * when the source field was empty.
     * Fields: source_id|upstream_step_id|upstream_sq_id|downstream_step_id|downstream_s_id|
     *         downstream_sq_id|operator_id|action_id|description|token|reference_value|
     *         default_upstream_value|override_upstream_value
     */
    private void insertRelationship(String[] fields, Long surveyId,
            Map<Long, Long> stepIdMap, Map<Long, Long> sectionsQuestionIdMap,
            Map<Long, Long> stepsSectionIdMap) {
        if (fields.length < 13) {
            throw new IllegalArgumentException("relationships requires 13 fields, got " + fields.length);
        }
        Long newUpstreamStepId = resolveNullable(parseLongOrNull(fields[1]), stepIdMap, "step (upstream)");
        Long newUpstreamSqId = resolveRequired(parseLongOrNull(fields[2]), sectionsQuestionIdMap, "sections_question (upstream_sq)");
        Long newDownstreamStepId = resolveNullable(parseLongOrNull(fields[3]), stepIdMap, "step (downstream)");
        Long newDownstreamSId = resolveNullable(parseLongOrNull(fields[4]), stepsSectionIdMap, "steps_section (downstream)");
        Long newDownstreamSqId = resolveNullable(parseLongOrNull(fields[5]), sectionsQuestionIdMap, "sections_question (downstream_sq)");

        Query query = em.createNativeQuery("""
                INSERT INTO survey.relationships
                    (id, survey_id, upstream_step_id, upstream_sq_id, downstream_step_id,
                     downstream_s_id, downstream_sq_id, operator_id, action_id, description,
                     token, reference_value, default_upstream_value, override_upstream_value)
                VALUES (nextval('survey.relationships_seq'), ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13)
                """);
        query.setParameter(1, surveyId);
        query.setParameter(2, newUpstreamStepId);
        query.setParameter(3, newUpstreamSqId);
        query.setParameter(4, newDownstreamStepId);
        query.setParameter(5, newDownstreamSId);
        query.setParameter(6, newDownstreamSqId);
        query.setParameter(7, parseIntOrNull(fields[6]));               // operator_id (static)
        query.setParameter(8, parseIntOrNull(fields[7]));               // action_id (static)
        query.setParameter(9, nullIfEmpty(fields[8]));                  // description
        query.setParameter(10, nullIfEmpty(fields[9]));                 // token
        query.setParameter(11, nullIfEmpty(fields[10]));                // reference_value
        query.setParameter(12, nullIfEmpty(fields[11]));                // default_upstream_value
        query.setParameter(13, nullIfEmpty(fields[12]));                // override_upstream_value
        query.executeUpdate();
    }

    /**
     * Inserts a new report row.
     * Fields: source_id|name|description|url|display_order
     */
    private void insertReport(String[] fields, Long surveyId) {
        if (fields.length < 5) {
            throw new IllegalArgumentException("reports requires 5 fields, got " + fields.length);
        }
        Query query = em.createNativeQuery("""
                INSERT INTO survey.reports (id, survey_id, name, description, url, display_order)
                VALUES (nextval('survey.reports_seq'), ?1, ?2, ?3, ?4, ?5)
                """);
        query.setParameter(1, surveyId);
        query.setParameter(2, nullIfEmpty(fields[1]));
        query.setParameter(3, nullIfEmpty(fields[2]));
        query.setParameter(4, nullIfEmpty(fields[3]));
        query.setParameter(5, parseIntOrNull(fields[4]));
        query.executeUpdate();
    }

    /**
     * Inserts a new post_survey_action row.
     * Fields: source_id|name|description|url|execution_order
     */
    private void insertPostSurveyAction(String[] fields, Long surveyId) {
        if (fields.length < 5) {
            throw new IllegalArgumentException("post_survey_actions requires 5 fields, got " + fields.length);
        }
        Query query = em.createNativeQuery("""
                INSERT INTO survey.post_survey_actions
                    (id, survey_id, name, description, url, execution_order)
                VALUES (nextval('survey.post_survey_actions_seq'), ?1, ?2, ?3, ?4, ?5)
                """);
        query.setParameter(1, surveyId);
        query.setParameter(2, nullIfEmpty(fields[1]));
        query.setParameter(3, nullIfEmpty(fields[2]));
        query.setParameter(4, nullIfEmpty(fields[3]));
        query.setParameter(5, parseIntOrNull(fields[4]));
        query.executeUpdate();
    }

    /**
     * Inserts a new dimension row, or reuses an existing row if name already exists.
     * Fields: source_id|name
     *
     * @return the new or existing dimension ID
     */
    private Long insertOrReuseDimension(String[] fields) {
        if (fields.length < 2) {
            throw new IllegalArgumentException("dimensions requires 2 fields, got " + fields.length);
        }
        String name = nullIfEmpty(fields[1]);

        // Check for existing dimension by name (unique constraint)
        Query existQuery = em.createNativeQuery(
                "SELECT id FROM survey.dimensions WHERE name = ?1");
        existQuery.setParameter(1, name);
        Long existingId = getLongResult(existQuery);
        if (existingId != null) {
            return existingId;
        }

        Query seqQuery = em.createNativeQuery("SELECT nextval('survey.dimensions_seq')");
        Long newId = ((Number) seqQuery.getSingleResult()).longValue();

        Query query = em.createNativeQuery("""
                INSERT INTO survey.dimensions (id, name)
                VALUES (?1, ?2)
                """);
        query.setParameter(1, newId);
        query.setParameter(2, name);
        query.executeUpdate();
        return newId;
    }

    /**
     * Inserts a new ontology row, or reuses an existing row if (name, tag) already exists
     * in the target system (since the unique constraint covers only those two columns).
     * Fields: source_id|name|tag|dimension
     *
     * @param dimensionIdMap mapping of old dimension IDs to new/existing dimension IDs
     * @return the new or existing ontology ID that should be used when resolving ontology_id references
     */
    private Long insertOrReuseOntology(String[] fields, Long surveyId, Map<Long, Long> dimensionIdMap) {
        if (fields.length < 4) {
            throw new IllegalArgumentException("ontology requires 4 fields, got " + fields.length);
        }
        String name = nullIfEmpty(fields[1]);
        String tag = nullIfEmpty(fields[2]);

        // Check for existing (name, tag) pair — unique constraint is only on these two columns
        Query existQuery = em.createNativeQuery(
                "SELECT id FROM survey.ontology WHERE name = ?1 AND tag = ?2");
        existQuery.setParameter(1, name);
        existQuery.setParameter(2, tag);
        Long existingId = getLongResult(existQuery);
        if (existingId != null) {
            return existingId;
        }

        // Resolve dimension ID via map (nullable)
        Long oldDimensionId = parseLongOrNull(fields[3]);
        Long newDimensionId = resolveNullable(oldDimensionId, dimensionIdMap, "dimension (ontology)");

        Query seqQuery = em.createNativeQuery("SELECT nextval('survey.ontology_seq')");
        Long newId = ((Number) seqQuery.getSingleResult()).longValue();

        Query query = em.createNativeQuery("""
                INSERT INTO survey.ontology (id, survey_id, name, tag, dimension)
                VALUES (?1, ?2, ?3, ?4, ?5)
                """);
        query.setParameter(1, newId);
        query.setParameter(2, surveyId);
        query.setParameter(3, name);
        query.setParameter(4, tag);
        query.setParameter(5, newDimensionId);
        query.executeUpdate();
        return newId;
    }

    /**
     * Inserts a new metadata row; all FK refs resolved via maps.
     * Fields: source_id|step_section_id|question_id|section_question_id|ontology_id|value
     */
    private void insertMetadata(String[] fields, Long surveyId,
            Map<Long, Long> stepsSectionIdMap, Map<Long, Long> questionIdMap,
            Map<Long, Long> sectionsQuestionIdMap, Map<Long, Long> ontologyIdMap) {
        if (fields.length < 6) {
            throw new IllegalArgumentException("metadata requires 6 fields, got " + fields.length);
        }
        Long newStepSectionId = resolveNullable(parseLongOrNull(fields[1]), stepsSectionIdMap, "steps_section (metadata)");
        Long newQuestionId = resolveNullable(parseLongOrNull(fields[2]), questionIdMap, "question (metadata)");
        Long newSectionQuestionId = resolveNullable(parseLongOrNull(fields[3]), sectionsQuestionIdMap, "sections_question (metadata)");
        Long newOntologyId = resolveRequired(parseLongOrNull(fields[4]), ontologyIdMap, "ontology (metadata)");

        Query query = em.createNativeQuery("""
                INSERT INTO survey.metadata
                    (id, survey_id, step_section_id, question_id, section_question_id, ontology_id, value)
                VALUES (nextval('survey.metadata_seq'), ?1, ?2, ?3, ?4, ?5, ?6)
                """);
        query.setParameter(1, surveyId);
        query.setParameter(2, newStepSectionId);
        query.setParameter(3, newQuestionId);
        query.setParameter(4, newSectionQuestionId);
        query.setParameter(5, newOntologyId);
        query.setParameter(6, nullIfEmpty(fields[5]));
        query.executeUpdate();
    }

    // -------------------------------------------------------------------------
    // Parser helpers
    // -------------------------------------------------------------------------

    /**
     * Parse pipe-delimited fields with escape sequence handling.
     */
    private String[] parseFields(String data) {
        List<String> fieldList = new ArrayList<>();
        StringBuilder current = new StringBuilder();
        boolean escaped = false;

        for (int i = 0; i < data.length(); i++) {
            char c = data.charAt(i);
            if (escaped) {
                switch (c) {
                    case '|' -> current.append('|');
                    case '\\' -> current.append('\\');
                    case 'n' -> current.append('\n');
                    case 'r' -> current.append('\r');
                    default -> { current.append('\\'); current.append(c); }
                }
                escaped = false;
            } else if (c == '\\') {
                escaped = true;
            } else if (c == '|') {
                fieldList.add(current.toString());
                current = new StringBuilder();
            } else {
                current.append(c);
            }
        }
        fieldList.add(current.toString());
        return fieldList.toArray(new String[0]);
    }

    // -------------------------------------------------------------------------
    // ID resolution helpers
    // -------------------------------------------------------------------------

    /**
     * Resolves a required (NOT NULL) FK reference. Throws if not found in map.
     */
    private Long resolveRequired(Long oldId, Map<Long, Long> map, String entityDesc) {
        if (oldId == null) {
            throw new IllegalStateException("Expected non-null source id for " + entityDesc);
        }
        Long newId = map.get(oldId);
        if (newId == null) {
            throw new IllegalStateException("No ID mapping found for " + entityDesc + " source_id=" + oldId);
        }
        return newId;
    }

    /**
     * Resolves a nullable FK reference. Returns null if oldId is null; throws if oldId is
     * non-null but has no mapping in the map.
     */
    private Long resolveNullable(Long oldId, Map<Long, Long> map, String entityDesc) {
        if (oldId == null) {
            return null;
        }
        Long newId = map.get(oldId);
        if (newId == null) {
            throw new IllegalStateException("No ID mapping found for " + entityDesc + " source_id=" + oldId);
        }
        return newId;
    }

    // -------------------------------------------------------------------------
    // Field parsing helpers
    // -------------------------------------------------------------------------

    /**
     * Converts empty input fields to {@code null} for nullable DB columns.
     *
     * @param value raw field value
     * @return {@code null} for empty input, otherwise the original string
     */
    private String nullIfEmpty(String value) {
        return (value == null || value.isEmpty()) ? null : value;
    }

    /**
     * Parses an integer field, returning {@code null} for empty or invalid input.
     *
     * @param value raw field value
     * @return parsed integer or {@code null}
     */
    private Integer parseIntOrNull(String value) {
        if (value == null || value.isEmpty()) {
            return null;
        }
        try {
            return Integer.parseInt(value.trim());
        } catch (NumberFormatException e) {
            return null;
        }
    }

    /**
     * Parses a long field, returning {@code null} for empty or invalid input.
     *
     * @param value raw field value
     * @return parsed long or {@code null}
     */
    private Long parseLongOrNull(String value) {
        if (value == null || value.isEmpty()) {
            return null;
        }
        try {
            return Long.parseLong(value.trim());
        } catch (NumberFormatException e) {
            return null;
        }
    }

    /**
     * Parses a boolean field with support for PostgreSQL-style {@code t} values.
     * Empty input defaults to {@code false}.
     *
     * @param value raw field value
     * @return parsed boolean value
     */
    private boolean parseBooleanOrFalse(String value) {
        if (value == null || value.isEmpty()) {
            return false;
        }
        return Boolean.parseBoolean(value) || "t".equalsIgnoreCase(value);
    }

    /**
     * Executes a scalar query expected to return one numeric ID.
     *
     * @param query scalar query
     * @return numeric result as {@link Long}, or {@code null} when no result/invalid type
     */
    private Long getLongResult(Query query) {
        try {
            Object result = query.getSingleResult();
            if (result instanceof Number n) {
                return n.longValue();
            }
            return null;
        } catch (Exception e) {
            return null;
        }
    }
}
