package com.elicitsoftware.service;

/*-
 * ***LICENSE_START***
 * Elicit Survey
 * %%
 * Copyright (C) 2025 The Regents of the University of Michigan - Rogel Cancer Center
 * %%
 * PolyForm Noncommercial License 1.0.0
 * <https://polyformproject.org/licenses/noncommercial/1.0.0>
 * ***LICENSE_END***
 */

import com.elicitsoftware.admin.upload.MultipartBody;
import jakarta.annotation.security.RolesAllowed;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;

/**
 * REST endpoint that imports a survey definition from an Elicit Survey export file.
 * <p>
 * Accepts files generated by {@link SurveyDefinitionExportResource} and uses parameterized
 * queries to safely import all survey definition data with fresh IDs.
 */
@Path("/secured/survey/import")
@ApplicationScoped
public class SurveyDefinitionImportResource {

    /**
     * Default constructor for CDI.
     */
    public SurveyDefinitionImportResource() {
        // CDI managed bean
    }

    @Inject
    SurveyDefinitionImportService surveyDefinitionImportService;

    /**
     * Import a survey definition from an Elicit Survey export file.
     * <p>
     * The file should be one generated by the survey export endpoint (.elicit format).
     * New IDs are allocated from sequences in this system — the original IDs from the
     * source system are not reused.
     *
     * @param multipartBody the multipart form data containing the export file in the "file" field
     * @return JSON response with import results or error information
     */
    @POST
    @RolesAllowed("elicit_admin")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @Produces(MediaType.APPLICATION_JSON)
    public Response importSurvey(MultipartBody multipartBody) {
        if (multipartBody.file == null) {
            return Response.status(Response.Status.BAD_REQUEST)
                    .entity(new ImportResponse(false, 0, "No file provided in the 'file' field", null))
                    .build();
        }

        try {
            SurveyDefinitionImportService.ImportResult result =
                    surveyDefinitionImportService.importFromFile(multipartBody.file);

            ImportResponse response = new ImportResponse(
                    result.isSuccess(),
                    result.getRecordsImported(),
                    result.isSuccess() ? "Import completed successfully"
                            : String.join("; ", result.getErrors()),
                    result.getCounts()
            );

            if (result.isSuccess()) {
                return Response.ok(response).build();
            } else {
                return Response.status(Response.Status.BAD_REQUEST)
                        .entity(response)
                        .build();
            }

        } catch (Exception e) {
            ImportResponse response = new ImportResponse(false, 0,
                    "Import failed: " + e.getMessage(), null);
            return Response.status(Response.Status.INTERNAL_SERVER_ERROR)
                    .entity(response)
                    .build();
        }
    }

    /**
     * Response DTO for survey definition import operations.
     */
    public static class ImportResponse {
        private boolean success;
        private int recordsImported;
        private String message;
        private java.util.Map<String, Integer> counts;

        /**
         * Default constructor for JSON serialization.
         */
        public ImportResponse() {
        }

        /**
         * Creates a new ImportResponse.
         *
         * @param success whether the import succeeded
         * @param recordsImported number of records imported
         * @param message status or error message
         * @param counts breakdown of records by table
         */
        public ImportResponse(boolean success, int recordsImported, String message,
                java.util.Map<String, Integer> counts) {
            this.success = success;
            this.recordsImported = recordsImported;
            this.message = message;
            this.counts = counts;
        }

        /**
         * Indicates whether the import succeeded.
         * @return true if import succeeded
         */
        public boolean isSuccess() { return success; }

        /**
         * Sets whether the import succeeded.
         * @param success whether import succeeded
         */
        public void setSuccess(boolean success) { this.success = success; }

        /**
         * Returns the number of records imported.
         * @return number of records imported
         */
        public int getRecordsImported() { return recordsImported; }

        /**
         * Sets the number of records imported.
         * @param recordsImported number of records imported
         */
        public void setRecordsImported(int recordsImported) { this.recordsImported = recordsImported; }

        /**
         * Returns the status or error message.
         * @return status or error message
         */
        public String getMessage() { return message; }

        /**
         * Sets the status or error message.
         * @param message status or error message
         */
        public void setMessage(String message) { this.message = message; }

        /**
         * Returns the breakdown of records imported by table.
         * @return breakdown of records by table
         */
        public java.util.Map<String, Integer> getCounts() { return counts; }

        /**
         * Sets the breakdown of records imported by table.
         * @param counts breakdown of records by table
         */
        public void setCounts(java.util.Map<String, Integer> counts) { this.counts = counts; }
    }
}
