package com.elicitsoftware.service;

/*-
 * ***LICENSE_START***
 * Elicit Survey
 * %%
 * Copyright (C) 2025 The Regents of the University of Michigan - Rogel Cancer Center
 * %%
 * PolyForm Noncommercial License 1.0.0
 * <https://polyformproject.org/licenses/noncommercial/1.0.0>
 * ***LICENSE_END***
 */

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.persistence.EntityManager;
import jakarta.persistence.Query;
import jakarta.transaction.Transactional;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * Imports survey definition data from export files generated by {@link SurveyDefinitionExportService}.
 * <p>
 * This service parses the custom Elicit Survey export format and uses parameterized queries
 * to safely insert data, preventing SQL injection attacks.
 * <p>
 * <strong>Format: ELICIT_SURVEY_EXPORT_V1</strong>
 * <ul>
 *   <li>Lines starting with # are comments/metadata</li>
 *   <li>Data lines: tablename: source_id|field1|field2|...</li>
 *   <li>Fields are pipe-delimited with escape sequences: \| \\ \n \r</li>
 *   <li>The source_id (first field) is the original ID from the exporting system — the
 *       durable Kimball Type 2 key for every table that has one, or the plain surrogate id
 *       for tables that aren't Type 2 versioned (surveys, reports, post_survey_actions,
 *       dimensions, ontology, metadata). It is used to resolve FK references; new IDs are
 *       allocated from sequences in this system.</li>
 *   <li>Every Type 2 table's trailing {@code version|effective_from|effective_to|
 *       published_by|published_comment} fields are parsed (so field-count
 *       validation and escaping still work) but their values are discarded — every imported
 *       row is created fresh as the current, version 0 row via each column's own
 *       schema default, never from the file. A file with an outdated
 *       {@code ELICIT_SURVEY_EXPORT_V1} header (pre-Kimball, no durable keys or Type 2
 *       columns) is rejected outright by the format-version check below — there is no
 *       surrogate-to-durable translation path.</li>
 * </ul>
 * <p>
 * <strong>ID generation strategy:</strong>
 * <ul>
 *   <li>surveys — explicit {@code nextval('survey.surveys_seq')}, captured as {@code newSurveyId}; {@code published_by}/{@code published_comment} left {@code NULL}. {@code survey_key} is the one exception to "everything is remapped fresh": carried over verbatim from the file, or freshly generated if absent, and rejected outright if a survey with that key already exists in this instance (use Update instead)</li>
 *   <li>select_groups — explicit nextval + durable id read back after insert, old→new durable stored in {@code selectGroupIdMap}</li>
 *   <li>select_items — inline nextval; select_group_id resolved via selectGroupIdMap (durable)</li>
 *   <li>steps — explicit nextval + durable id read back after insert, old→new durable stored in {@code stepIdMap}</li>
 *   <li>sections — explicit nextval + durable id read back after insert, old→new durable stored in {@code sectionIdMap}</li>
 *   <li>steps_sections — explicit nextval + durable id read back after insert, old→new durable stored in {@code stepsSectionIdMap}</li>
 *   <li>questions — explicit nextval + durable id read back after insert, old→new durable stored in {@code questionIdMap}</li>
 *   <li>sections_questions — explicit nextval + durable id read back after insert, old→new durable stored in {@code sectionsQuestionIdMap}</li>
 *   <li>relationships — inline nextval; all FK refs resolved via the (durable) maps above</li>
 *   <li>reports — inline nextval; {@code report_key} carried over verbatim (or freshly generated)</li>
 *   <li>post_survey_actions — inline nextval; {@code post_survey_action_key} carried over verbatim (or freshly generated)</li>
 *   <li>dimensions — explicit nextval or reuse existing row by name (shared global lookup — reuse wins over the file's own key); stored in {@code dimensionIdMap}</li>
 *   <li>ontology — explicit nextval or reuse existing row by (name, tag); dimension resolved via dimensionIdMap; stored in {@code ontologyIdMap}</li>
 *   <li>metadata — inline nextval (metadata itself is not Type 2 versioned); its 3 FK-ish columns resolved via the (durable) maps above; {@code metadata_key} carried over verbatim (or freshly generated)</li>
 * </ul>
 * <p>
 * Every map above is old-durable-id → new-durable-id (not surrogate id) — nothing downstream
 * of any insert ever needs the freshly-allocated surrogate {@code id}, since every
 * cross-table FK in the post-Kimball schema targets a durable id.
 * <p>
 * Static lookup table references (type_id, operator_id, action_id) are imported
 * verbatim — they must exist in the target system with the same IDs.
 * <p>
 * The entire import is wrapped in a single {@code @Transactional} method — any failure
 * rolls back all rows inserted in that call.
 *
 * @see SurveyDefinitionExportService
 */
@ApplicationScoped
public class SurveyDefinitionImportService {

    /**
     * Default constructor for CDI.
     */
    public SurveyDefinitionImportService() {
        // CDI managed bean
    }

    private static final String FORMAT_VERSION = SurveyDefinitionExportService.FORMAT_VERSION;

    @Inject
    EntityManager em;

    @Inject
    SurveyLogService surveyLogService;

    /**
     * Result of resolving/inserting the {@code surveys} row: its freshly-allocated
     * surrogate id and the {@code survey_key} that ended up on the row (carried over from
     * the file, or freshly generated if the file predates key assignment) — captured
     * separately from the id so the caller can log the key even if a later line in the
     * same file fails.
     */
    private record SurveyInsertResult(Long id, UUID surveyKey) {
    }

    /**
     * Result of an import operation.
     */
    public static class ImportResult {
        private final boolean success;
        private final int recordsImported;
        private final List<String> errors;
        private final Map<String, Integer> counts;

        /**
         * Creates a new ImportResult.
         *
         * @param success whether the import succeeded
         * @param recordsImported number of records imported
         * @param errors list of error messages
         * @param counts breakdown of records by table
         */
        public ImportResult(boolean success, int recordsImported, List<String> errors, Map<String, Integer> counts) {
            this.success = success;
            this.recordsImported = recordsImported;
            this.errors = errors;
            this.counts = counts;
        }

        /**
         * Indicates whether the import succeeded.
         * @return true if import succeeded
         */
        public boolean isSuccess() { return success; }

        /**
         * Returns the number of records imported.
         * @return number of records imported
         */
        public int getRecordsImported() { return recordsImported; }

        /**
         * Returns the list of error messages from import.
         * @return list of error messages
         */
        public List<String> getErrors() { return errors; }

        /**
         * Returns the breakdown of records imported by table.
         * @return breakdown of records by table
         */
        public Map<String, Integer> getCounts() { return counts; }
    }

    /**
     * Imports survey definition data from an Elicit Survey export file.
     * <p>
     * Data lines must appear in dependency order as written by the exporter:
     * surveys → select_groups → select_items → steps → sections → steps_sections
     * → questions → sections_questions → relationships → reports → post_survey_actions
     * → dimensions → ontology → metadata
     * <p>
     * Uses parameterized queries to prevent SQL injection.
     *
     * @param inputStream the input stream containing the export file
     * @param fileName the uploaded file's original name, for the {@code survey_log} audit row
     * @return ImportResult with success status, counts, and any errors
     */
    @Transactional
    public ImportResult importFromFile(InputStream inputStream, String fileName) {
        List<String> errors = new ArrayList<>();
        // Captured as soon as the surveys: line is parsed, so a later line's failure can
        // still be logged against the right survey_key — see logAttempt() at the bottom.
        SurveyInsertResult[] surveyInsert = new SurveyInsertResult[1];
        Map<String, Integer> counts = new HashMap<>();
        counts.put("surveys", 0);
        counts.put("select_groups", 0);
        counts.put("select_items", 0);
        counts.put("steps", 0);
        counts.put("sections", 0);
        counts.put("steps_sections", 0);
        counts.put("questions", 0);
        counts.put("sections_questions", 0);
        counts.put("relationships", 0);
        counts.put("reports", 0);
        counts.put("post_survey_actions", 0);
        counts.put("dimensions", 0);
        counts.put("ontology", 0);
        counts.put("metadata", 0);

        // State: new survey ID and old→new ID maps for each entity type
        Long newSurveyId = null;
        Map<Long, Long> selectGroupIdMap = new HashMap<>();
        Map<Long, Long> stepIdMap = new HashMap<>();
        Map<Long, Long> sectionIdMap = new HashMap<>();
        Map<Long, Long> stepsSectionIdMap = new HashMap<>();
        Map<Long, Long> questionIdMap = new HashMap<>();
        Map<Long, Long> sectionsQuestionIdMap = new HashMap<>();
        Map<Long, Long> dimensionIdMap = new HashMap<>();
        Map<Long, Long> ontologyIdMap = new HashMap<>();

        int lineNumber = 0;
        // Parsed from the "# survey_revision:" header, before any data line. Held in a
        // single-element array so logAttempt() can read whatever was parsed at the point a
        // failure occurred, including from inside the catch blocks below.
        OffsetDateTime[] fileRevision = new OffsetDateTime[1];

        try (BufferedReader reader = new BufferedReader(
                new InputStreamReader(inputStream, StandardCharsets.UTF_8))) {
            String line;
            boolean versionValidated = false;

            while ((line = reader.readLine()) != null) {
                lineNumber++;
                line = line.trim();

                if (line.isEmpty()) {
                    continue;
                }

                if (line.startsWith("#")) {
                    if (line.contains(FORMAT_VERSION)) {
                        versionValidated = true;
                    }
                    try {
                        OffsetDateTime parsed = SurveyDefinitionFileFields.parseRevisionHeader(line);
                        if (parsed != null) {
                            fileRevision[0] = parsed;
                        }
                    } catch (IllegalArgumentException e) {
                        errors.add("Line " + lineNumber + ": " + e.getMessage());
                        logAttempt(surveyInsert[0], fileName, false, errors, counts, fileRevision[0]);
                        return new ImportResult(false, 0, errors, counts);
                    }
                    continue;
                }

                if (!versionValidated) {
                    errors.add("Line " + lineNumber + ": File does not start with valid format header (expected # "
                            + FORMAT_VERSION + ")");
                    logAttempt(surveyInsert[0], fileName, false, errors, counts, fileRevision[0]);
                    return new ImportResult(false, 0, errors, counts);
                }

                // Data line: "tablename: field1|field2|..."
                int colonIndex = line.indexOf(':');
                if (colonIndex < 0) {
                    errors.add("Line " + lineNumber + ": Invalid format, missing colon separator");
                    continue;
                }

                String tableName = line.substring(0, colonIndex).trim().toLowerCase();
                String fieldData = line.substring(colonIndex + 1).trim();
                String[] fields = parseFields(fieldData);

                if (SurveyDefinitionFileFields.isRetired(tableName, fields)) {
                    // A removal made in the authoring tool: nothing to install here (BR: the
                    // element never existed at this site), but count it so the summary explains
                    // why the file's header count and the installed count differ.
                    counts.merge("skipped_retired", 1, Integer::sum);
                    continue;
                }
                try {
                    switch (tableName) {
                        case "surveys": {
                            if (newSurveyId != null) {
                                errors.add("Line " + lineNumber + ": Multiple survey records found; only one supported per file");
                                continue;
                            }
                            surveyInsert[0] = insertSurvey(fields);
                            newSurveyId = surveyInsert[0].id();
                            counts.merge("surveys", 1, Integer::sum);
                            break;
                        }
                        case "select_groups": {
                            if (newSurveyId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert select_group before survey");
                                continue;
                            }
                            Long sourceId = parseLongOrNull(fields[0]);
                            Long newId = insertSelectGroup(fields, newSurveyId);
                            selectGroupIdMap.put(sourceId, newId);
                            counts.merge("select_groups", 1, Integer::sum);
                            break;
                        }
                        case "select_items": {
                            if (newSurveyId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert select_item before survey");
                                continue;
                            }
                            insertSelectItem(fields, newSurveyId, selectGroupIdMap);
                            counts.merge("select_items", 1, Integer::sum);
                            break;
                        }
                        case "steps": {
                            if (newSurveyId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert step before survey");
                                continue;
                            }
                            Long sourceId = parseLongOrNull(fields[0]);
                            Long newId = insertStep(fields, newSurveyId);
                            stepIdMap.put(sourceId, newId);
                            counts.merge("steps", 1, Integer::sum);
                            break;
                        }
                        case "sections": {
                            if (newSurveyId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert section before survey");
                                continue;
                            }
                            Long sourceId = parseLongOrNull(fields[0]);
                            Long newId = insertSection(fields, newSurveyId);
                            sectionIdMap.put(sourceId, newId);
                            counts.merge("sections", 1, Integer::sum);
                            break;
                        }
                        case "steps_sections": {
                            if (newSurveyId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert steps_section before survey");
                                continue;
                            }
                            Long sourceId = parseLongOrNull(fields[0]);
                            Long newId = insertStepsSection(fields, newSurveyId, stepIdMap, sectionIdMap);
                            stepsSectionIdMap.put(sourceId, newId);
                            counts.merge("steps_sections", 1, Integer::sum);
                            break;
                        }
                        case "questions": {
                            if (newSurveyId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert question before survey");
                                continue;
                            }
                            Long sourceId = parseLongOrNull(fields[0]);
                            Long newId = insertQuestion(fields, newSurveyId, selectGroupIdMap);
                            questionIdMap.put(sourceId, newId);
                            counts.merge("questions", 1, Integer::sum);
                            break;
                        }
                        case "sections_questions": {
                            if (newSurveyId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert sections_question before survey");
                                continue;
                            }
                            Long sourceId = parseLongOrNull(fields[0]);
                            Long newId = insertSectionsQuestion(fields, newSurveyId, questionIdMap, sectionIdMap);
                            sectionsQuestionIdMap.put(sourceId, newId);
                            counts.merge("sections_questions", 1, Integer::sum);
                            break;
                        }
                        case "relationships": {
                            if (newSurveyId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert relationship before survey");
                                continue;
                            }
                            insertRelationship(fields, newSurveyId, stepIdMap, sectionsQuestionIdMap, stepsSectionIdMap);
                            counts.merge("relationships", 1, Integer::sum);
                            break;
                        }
                        case "reports": {
                            if (newSurveyId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert report before survey");
                                continue;
                            }
                            insertReport(fields, newSurveyId);
                            counts.merge("reports", 1, Integer::sum);
                            break;
                        }
                        case "post_survey_actions": {
                            if (newSurveyId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert post_survey_action before survey");
                                continue;
                            }
                            insertPostSurveyAction(fields, newSurveyId);
                            counts.merge("post_survey_actions", 1, Integer::sum);
                            break;
                        }
                        case "dimensions": {
                            Long sourceId = parseLongOrNull(fields[0]);
                            Long newId = insertOrReuseDimension(fields);
                            dimensionIdMap.put(sourceId, newId);
                            counts.merge("dimensions", 1, Integer::sum);
                            break;
                        }
                        case "ontology": {
                            if (newSurveyId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert ontology before survey");
                                continue;
                            }
                            Long sourceId = parseLongOrNull(fields[0]);
                            Long newId = insertOrReuseOntology(fields, newSurveyId, dimensionIdMap);
                            ontologyIdMap.put(sourceId, newId);
                            counts.merge("ontology", 1, Integer::sum);
                            break;
                        }
                        case "metadata": {
                            if (newSurveyId == null) {
                                errors.add("Line " + lineNumber + ": Cannot insert metadata before survey");
                                continue;
                            }
                            insertMetadata(fields, newSurveyId, stepsSectionIdMap, questionIdMap,
                                    sectionsQuestionIdMap, ontologyIdMap);
                            counts.merge("metadata", 1, Integer::sum);
                            break;
                        }
                        default:
                            errors.add("Line " + lineNumber + ": Unknown table: " + tableName);
                    }
                } catch (Exception e) {
                    errors.add("Line " + lineNumber + ": " + e.getMessage());
                    logAttempt(surveyInsert[0], fileName, false, errors, counts, fileRevision[0]);
                    throw new RuntimeException("Import failed at line " + lineNumber + ": " + e.getMessage(), e);
                }
            }

            if (!versionValidated) {
                errors.add("File does not contain valid format header");
                logAttempt(surveyInsert[0], fileName, false, errors, counts, fileRevision[0]);
                return new ImportResult(false, 0, errors, counts);
            }

            int total = counts.values().stream().mapToInt(Integer::intValue).sum();
            logAttempt(surveyInsert[0], fileName, errors.isEmpty(), errors, counts, fileRevision[0]);
            return new ImportResult(errors.isEmpty(), total, errors, counts);

        } catch (IOException e) {
            errors.add("Failed to read file: " + e.getMessage());
            logAttempt(surveyInsert[0], fileName, false, errors, counts, fileRevision[0]);
            return new ImportResult(false, 0, errors, counts);
        }
    }

    /**
     * Records this import attempt to {@code survey.survey_log} — success or failure.
     * <p>
     * Import always creates a brand-new survey within this same {@code @Transactional} method,
     * so on failure that row is rolled back and will never exist — {@link SurveyLogService}'s
     * {@code REQUIRES_NEW} failure log can therefore never reference it by id (only the key is
     * recorded). On success, the survey row and this log entry commit together in the same
     * transaction, so referencing it by id is safe.
     *
     * @param surveyInsert the resolved survey id/key, or {@code null} if the file never got
     *     far enough to parse a {@code surveys:} line
     * @param fileName the uploaded file's name
     * @param success whether the import succeeded
     * @param errors accumulated error messages (used as the failure reason when not empty)
     * @param counts per-table counts (used to build the success summary)
     */
    private void logAttempt(SurveyInsertResult surveyInsert, String fileName, boolean success,
            List<String> errors, Map<String, Integer> counts, OffsetDateTime revision) {
        UUID surveyKey = surveyInsert == null ? null : surveyInsert.surveyKey();
        if (success && surveyInsert != null) {
            surveyLogService.logSuccess(surveyInsert.id(), surveyKey, "IMPORT", fileName, counts.toString(), revision);
        } else {
            surveyLogService.logFailure(null, surveyKey, "IMPORT", fileName, String.join("; ", errors), revision);
        }
    }

    // -------------------------------------------------------------------------
    // Insert methods
    // -------------------------------------------------------------------------

    /**
     * Inserts a new survey row using a fresh sequence ID.
     * Fields: source_id|survey_key|name|display_order|title|description|initial_display_key|post_survey_url|published_by|published_comment
     * <p>
     * Note: display_order is computed as MAX(display_order) + 1 to avoid unique constraint
     * violations, rather than using the value from the export file. published_by/published_comment
     * are parsed for field-count validation but not inserted — left {@code NULL} (the survey is
     * being installed, not authored).
     * <p>
     * {@code survey_key} is the one identifier in this file that must be preserved verbatim
     * rather than reallocated (BR-061) — carried over from the file if present, or freshly
     * generated if the file predates key assignment. If a survey with that key already
     * exists in this instance, the create-import is rejected (BR-062): the file describes a
     * survey that has already been deployed here, and must be applied via Update instead.
     */
    private SurveyInsertResult insertSurvey(String[] fields) {
        if (fields.length < 10) {
            throw new IllegalArgumentException("surveys requires 10 fields, got " + fields.length);
        }
        UUID surveyKey = resolveSurveyKey(fields[1]);

        Query existQuery = em.createNativeQuery("SELECT id FROM survey.surveys WHERE survey_key = ?1");
        existQuery.setParameter(1, surveyKey);
        Long existingId = getLongResult(existQuery);
        if (existingId != null) {
            throw new IllegalStateException("A survey with survey_key " + surveyKey
                    + " already exists in this instance (id=" + existingId
                    + "); use Update instead of Import to apply changes to it.");
        }

        Query seqQuery = em.createNativeQuery("SELECT nextval('survey.surveys_seq')");
        Long newId = ((Number) seqQuery.getSingleResult()).longValue();

        // Compute next display_order as max + 1 to avoid unique constraint violations
        Query maxOrderQuery = em.createNativeQuery(
                "SELECT COALESCE(MAX(display_order), 0) + 1 FROM survey.surveys");
        Integer nextDisplayOrder = ((Number) maxOrderQuery.getSingleResult()).intValue();

        Query query = em.createNativeQuery("""
                INSERT INTO survey.surveys
                    (id, survey_key, name, display_order, title, description, initial_display_key, post_survey_url)
                VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
                """);
        query.setParameter(1, newId);
        query.setParameter(2, surveyKey);
        query.setParameter(3, nullIfEmpty(fields[2]));
        query.setParameter(4, nextDisplayOrder);
        query.setParameter(5, nullIfEmpty(fields[4]));
        query.setParameter(6, nullIfEmpty(fields[5]));
        // Rebased onto newId: the file carries the exporting deployment's survey id, which is
        // not the one allocated here. See SurveyDefinitionFileFields#rebaseDisplayKey.
        query.setParameter(7, SurveyDefinitionFileFields.rebaseDisplayKey(fields[6], newId));
        query.setParameter(8, nullIfEmpty(fields[7]));
        query.executeUpdate();
        return new SurveyInsertResult(newId, surveyKey);
    }

    /**
     * Resolves the {@code survey_key} to use for a create-import: the file's own value if
     * present, or a freshly generated one if the file predates key assignment (BR-061).
     */
    private UUID resolveSurveyKey(String rawSurveyKey) {
        String value = nullIfEmpty(rawSurveyKey);
        if (value == null) {
            return UUID.randomUUID();
        }
        try {
            return UUID.fromString(value.trim());
        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException("Invalid survey_key in file: " + value, e);
        }
    }

    /**
     * Resolves the {@code element_key} to use for one structural row on a create-import:
     * the file's own value if present, or a freshly generated one if the file predates key
     * assignment — same pattern as {@link #resolveSurveyKey(String)}, one level down. Unlike
     * the durable id (which is always reallocated fresh per-instance), this value is carried
     * over verbatim so the same logical element can be recognized across separate deployments.
     */
    private UUID resolveElementKey(String rawElementKey) {
        String value = nullIfEmpty(rawElementKey);
        if (value == null) {
            return UUID.randomUUID();
        }
        try {
            return UUID.fromString(value.trim());
        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException("Invalid element_key in file: " + value, e);
        }
    }

    /**
     * Inserts a new select_group row. Type 2 columns (version/effective_from/effective_to/
     * durable id) are left to their schema defaults; published_by/published_comment
     * are parsed but not inserted (left {@code NULL}). {@code element_key} is carried over
     * verbatim from the file (or freshly generated if absent, BR-061-style) — see
     * {@link #resolveElementKey(String)}.
     * Fields: source_id|element_key|name|description|data_type|version|effective_from|effective_to|published_by|published_comment
     *
     * @return the new row's durable {@code select_group_id}
     */
    private Long insertSelectGroup(String[] fields, Long surveyId) {
        if (fields.length < 10) {
            throw new IllegalArgumentException("select_groups requires 10 fields, got " + fields.length);
        }
        UUID elementKey = resolveElementKey(fields[1]);
        Query seqQuery = em.createNativeQuery("SELECT nextval('survey.select_groups_seq')");
        Long newId = ((Number) seqQuery.getSingleResult()).longValue();

        String dataType = nullIfEmpty(fields[4]);

        Query query = em.createNativeQuery("""
                INSERT INTO survey.select_groups (id, survey_id, select_group_key, name, description, data_type)
                VALUES (?1, ?2, ?3, ?4, ?5, ?6)
                """);
        query.setParameter(1, newId);
        query.setParameter(2, surveyId);
        query.setParameter(3, elementKey);
        query.setParameter(4, nullIfEmpty(fields[2]));
        query.setParameter(5, nullIfEmpty(fields[3]));
        query.setParameter(6, dataType != null ? dataType : "Text");
        query.executeUpdate();
        return getDurableId("select_group_id", "survey.select_groups", newId);
    }

    /**
     * Inserts a new select_item row; select_group_id (durable) resolved via selectGroupIdMap.
     * {@code element_key} carried over verbatim (or freshly generated) — see
     * {@link #resolveElementKey(String)}.
     * Fields: source_id|element_key|select_group_id|display_text|display_order|coded_value|version|effective_from|effective_to|published_by|published_comment
     */
    private void insertSelectItem(String[] fields, Long surveyId, Map<Long, Long> selectGroupIdMap) {
        if (fields.length < 11) {
            throw new IllegalArgumentException("select_items requires 11 fields, got " + fields.length);
        }
        UUID elementKey = resolveElementKey(fields[1]);
        Long oldGroupId = parseLongOrNull(fields[2]);
        Long newGroupId = resolveRequired(oldGroupId, selectGroupIdMap, "select_group (for select_item)");

        Query query = em.createNativeQuery("""
                INSERT INTO survey.select_items
                    (id, survey_id, select_item_key, select_group_id, display_text, display_order, coded_value)
                VALUES (nextval('survey.select_items_seq'), ?1, ?2, ?3, ?4, ?5, ?6)
                """);
        query.setParameter(1, surveyId);
        query.setParameter(2, elementKey);
        query.setParameter(3, newGroupId);
        query.setParameter(4, nullIfEmpty(fields[3]));
        query.setParameter(5, parseIntOrNull(fields[4]));
        query.setParameter(6, nullIfEmpty(fields[5]));
        query.executeUpdate();
    }

    /**
     * Inserts a new step row. {@code element_key} carried over verbatim (or freshly
     * generated) — see {@link #resolveElementKey(String)}.
     * Fields: source_id|element_key|display_order|name|dimension_name|description|version|effective_from|effective_to|published_by|published_comment
     * <p>
     * Note: If dimension_name is empty, it defaults to the step name to satisfy NOT NULL constraint.
     *
     * @return the new row's durable {@code step_id}
     */
    private Long insertStep(String[] fields, Long surveyId) {
        if (fields.length < 11) {
            throw new IllegalArgumentException("steps requires 11 fields, got " + fields.length);
        }
        UUID elementKey = resolveElementKey(fields[1]);
        Query seqQuery = em.createNativeQuery("SELECT nextval('survey.steps_seq')");
        Long newId = ((Number) seqQuery.getSingleResult()).longValue();

        String name = nullIfEmpty(fields[3]);
        String dimensionName = nullIfEmpty(fields[4]);
        // Default dimension_name to step name if empty (NOT NULL constraint)
        if (dimensionName == null) {
            dimensionName = name != null ? name : "";
        }

        Query query = em.createNativeQuery("""
                INSERT INTO survey.steps
                    (id, survey_id, step_key, display_order, name, dimension_name, description)
                VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
                """);
        query.setParameter(1, newId);
        query.setParameter(2, surveyId);
        query.setParameter(3, elementKey);
        query.setParameter(4, parseIntOrNull(fields[2]));
        query.setParameter(5, name);
        query.setParameter(6, dimensionName);
        query.setParameter(7, nullIfEmpty(fields[5]));
        query.executeUpdate();
        return getDurableId("step_id", "survey.steps", newId);
    }

    /**
     * Inserts a new section row. {@code element_key} carried over verbatim (or freshly
     * generated) — see {@link #resolveElementKey(String)}.
     * Fields: source_id|element_key|display_order|name|dimension_name|description|version|effective_from|effective_to|published_by|published_comment
     * <p>
     * Note: If dimension_name is empty, it defaults to the section name to satisfy NOT NULL constraint.
     *
     * @return the new row's durable {@code section_id}
     */
    private Long insertSection(String[] fields, Long surveyId) {
        if (fields.length < 11) {
            throw new IllegalArgumentException("sections requires 11 fields, got " + fields.length);
        }
        UUID elementKey = resolveElementKey(fields[1]);
        Query seqQuery = em.createNativeQuery("SELECT nextval('survey.sections_seq')");
        Long newId = ((Number) seqQuery.getSingleResult()).longValue();

        String name = nullIfEmpty(fields[3]);
        String dimensionName = nullIfEmpty(fields[4]);
        // Default dimension_name to section name if empty (NOT NULL constraint)
        if (dimensionName == null) {
            dimensionName = name != null ? name : "";
        }

        Query query = em.createNativeQuery("""
                INSERT INTO survey.sections
                    (id, survey_id, section_key, display_order, name, dimension_name, description)
                VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
                """);
        query.setParameter(1, newId);
        query.setParameter(2, surveyId);
        query.setParameter(3, elementKey);
        query.setParameter(4, parseIntOrNull(fields[2]));
        query.setParameter(5, name);
        query.setParameter(6, dimensionName);
        query.setParameter(7, nullIfEmpty(fields[5]));
        query.executeUpdate();
        return getDurableId("section_id", "survey.sections", newId);
    }

    /**
     * Inserts a new steps_sections row; step_id and section_id (durable) resolved via maps.
     * {@code element_key} carried over verbatim (or freshly generated) — see
     * {@link #resolveElementKey(String)}.
     * Fields: source_id|element_key|step_id|step_display_order|section_id|section_display_order|display_key|version|effective_from|effective_to|published_by|published_comment
     *
     * @return the new row's durable {@code steps_sections_id}
     */
    private Long insertStepsSection(String[] fields, Long surveyId,
            Map<Long, Long> stepIdMap, Map<Long, Long> sectionIdMap) {
        if (fields.length < 12) {
            throw new IllegalArgumentException("steps_sections requires 12 fields, got " + fields.length);
        }
        UUID elementKey = resolveElementKey(fields[1]);
        Long newStepId = resolveRequired(parseLongOrNull(fields[2]), stepIdMap, "step (for steps_sections)");
        Long newSectionId = resolveRequired(parseLongOrNull(fields[4]), sectionIdMap, "section (for steps_sections)");

        Query seqQuery = em.createNativeQuery("SELECT nextval('survey.steps_sections_seq')");
        Long newId = ((Number) seqQuery.getSingleResult()).longValue();

        Query query = em.createNativeQuery("""
                INSERT INTO survey.steps_sections
                    (id, survey_id, steps_sections_key, step_id, step_display_order, section_id, section_display_order, display_key)
                VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
                """);
        query.setParameter(1, newId);
        query.setParameter(2, surveyId);
        query.setParameter(3, elementKey);
        query.setParameter(4, newStepId);
        query.setParameter(5, parseIntOrNull(fields[3]));
        query.setParameter(6, newSectionId);
        query.setParameter(7, parseIntOrNull(fields[5]));
        // Rebased onto this deployment's surveyId — see SurveyDefinitionFileFields#rebaseDisplayKey.
        query.setParameter(8, SurveyDefinitionFileFields.rebaseDisplayKey(fields[6], surveyId));
        query.executeUpdate();
        return getDurableId("steps_sections_id", "survey.steps_sections", newId);
    }

    /**
     * Inserts a new question row; select_group_id (durable) resolved via selectGroupIdMap (nullable).
     * {@code element_key} carried over verbatim (or freshly generated) — see
     * {@link #resolveElementKey(String)}.
     * Fields: source_id|element_key|type_id|text|short_text|tool_tip|required|min_value|max_value|
     *         validation_text|select_group_id|mask|placeholder|default_value|variant|
     *         version|effective_from|effective_to|published_by|published_comment
     *
     * @return the new row's durable {@code question_id}
     */
    private Long insertQuestion(String[] fields, Long surveyId, Map<Long, Long> selectGroupIdMap) {
        if (fields.length < 20) {
            throw new IllegalArgumentException("questions requires 20 fields, got " + fields.length);
        }
        UUID elementKey = resolveElementKey(fields[1]);
        Long oldSelectGroupId = parseLongOrNull(fields[10]);
        Long newSelectGroupId = null;
        if (oldSelectGroupId != null) {
            newSelectGroupId = resolveRequired(oldSelectGroupId, selectGroupIdMap, "select_group (for question)");
        }

        Query seqQuery = em.createNativeQuery("SELECT nextval('survey.questions_seq')");
        Long newId = ((Number) seqQuery.getSingleResult()).longValue();

        Query query = em.createNativeQuery("""
                INSERT INTO survey.questions
                    (id, survey_id, question_key, type_id, text, short_text, tool_tip, required,
                     min_value, max_value, validation_text, select_group_id,
                     mask, placeholder, default_value, variant)
                VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16)
                """);
        query.setParameter(1, newId);
        query.setParameter(2, surveyId);
        query.setParameter(3, elementKey);
        query.setParameter(4, parseIntOrNull(fields[2]));               // type_id (static)
        query.setParameter(5, nullIfEmpty(fields[3]));                  // text
        query.setParameter(6, nullIfEmpty(fields[4]));                  // short_text
        query.setParameter(7, nullIfEmpty(fields[5]));                  // tool_tip
        query.setParameter(8, parseBooleanOrFalse(fields[6]));          // required
        query.setParameter(9, parseIntOrNull(fields[7]));               // min_value
        query.setParameter(10, parseIntOrNull(fields[8]));              // max_value
        query.setParameter(11, nullIfEmpty(fields[9]));                 // validation_text
        query.setParameter(12, newSelectGroupId);                       // select_group_id (resolved)
        query.setParameter(13, nullIfEmpty(fields[11]));                // mask
        query.setParameter(14, nullIfEmpty(fields[12]));                // placeholder
        query.setParameter(15, nullIfEmpty(fields[13]));                // default_value
        query.setParameter(16, nullIfEmpty(fields[14]));                // variant
        query.executeUpdate();
        return getDurableId("question_id", "survey.questions", newId);
    }

    /**
     * Inserts a new sections_questions row; question_id and section_id (durable) resolved via maps.
     * {@code element_key} carried over verbatim (or freshly generated) — see
     * {@link #resolveElementKey(String)}.
     * Fields: source_id|element_key|question_id|section_id|display_order|version|effective_from|effective_to|published_by|published_comment
     *
     * @return the new row's durable {@code sections_question_id}
     */
    private Long insertSectionsQuestion(String[] fields, Long surveyId,
            Map<Long, Long> questionIdMap, Map<Long, Long> sectionIdMap) {
        if (fields.length < 10) {
            throw new IllegalArgumentException("sections_questions requires 10 fields, got " + fields.length);
        }
        UUID elementKey = resolveElementKey(fields[1]);
        Long newQuestionId = resolveRequired(parseLongOrNull(fields[2]), questionIdMap, "question (for sections_questions)");
        Long newSectionId = resolveRequired(parseLongOrNull(fields[3]), sectionIdMap, "section (for sections_questions)");

        Query seqQuery = em.createNativeQuery("SELECT nextval('survey.sections_questions_seq')");
        Long newId = ((Number) seqQuery.getSingleResult()).longValue();

        Query query = em.createNativeQuery("""
                INSERT INTO survey.sections_questions
                    (id, survey_id, sections_question_key, question_id, section_id, display_order)
                VALUES (?1, ?2, ?3, ?4, ?5, ?6)
                """);
        query.setParameter(1, newId);
        query.setParameter(2, surveyId);
        query.setParameter(3, elementKey);
        query.setParameter(4, newQuestionId);
        query.setParameter(5, newSectionId);
        query.setParameter(6, parseIntOrNull(fields[4]));
        query.executeUpdate();
        return getDurableId("sections_question_id", "survey.sections_questions", newId);
    }

    /**
     * Inserts a new relationship row; all FK refs (durable) resolved via maps. Nullable FKs
     * become null when the source field was empty. {@code element_key} carried over verbatim
     * (or freshly generated) — see {@link #resolveElementKey(String)}.
     * Fields: source_id|element_key|upstream_step_id|upstream_sq_id|downstream_step_id|downstream_ss_id|
     *         downstream_sq_id|operator_id|action_id|description|token|reference_value|
     *         default_upstream_value|override_upstream_value|version|effective_from|
     *         effective_to|published_by|published_comment
     */
    private void insertRelationship(String[] fields, Long surveyId,
            Map<Long, Long> stepIdMap, Map<Long, Long> sectionsQuestionIdMap,
            Map<Long, Long> stepsSectionIdMap) {
        if (fields.length < 19) {
            throw new IllegalArgumentException("relationships requires 19 fields, got " + fields.length);
        }
        UUID elementKey = resolveElementKey(fields[1]);
        Long newUpstreamStepId = resolveNullable(parseLongOrNull(fields[2]), stepIdMap, "step (upstream)");
        Long newUpstreamSqId = resolveRequired(parseLongOrNull(fields[3]), sectionsQuestionIdMap, "sections_question (upstream_sq)");
        Long newDownstreamStepId = resolveNullable(parseLongOrNull(fields[4]), stepIdMap, "step (downstream)");
        Long newDownstreamSsId = resolveNullable(parseLongOrNull(fields[5]), stepsSectionIdMap, "steps_section (downstream_ss)");
        Long newDownstreamSqId = resolveNullable(parseLongOrNull(fields[6]), sectionsQuestionIdMap, "sections_question (downstream_sq)");

        Query query = em.createNativeQuery("""
                INSERT INTO survey.relationships
                    (id, survey_id, relationship_key, upstream_step_id, upstream_sq_id, downstream_step_id,
                     downstream_ss_id, downstream_sq_id, operator_id, action_id, description,
                     token, reference_value, default_upstream_value, override_upstream_value)
                VALUES (nextval('survey.relationships_seq'), ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14)
                """);
        query.setParameter(1, surveyId);
        query.setParameter(2, elementKey);
        query.setParameter(3, newUpstreamStepId);
        query.setParameter(4, newUpstreamSqId);
        query.setParameter(5, newDownstreamStepId);
        query.setParameter(6, newDownstreamSsId);
        query.setParameter(7, newDownstreamSqId);
        query.setParameter(8, parseIntOrNull(fields[7]));               // operator_id (static)
        query.setParameter(9, parseIntOrNull(fields[8]));               // action_id (static)
        query.setParameter(10, nullIfEmpty(fields[9]));                 // description
        query.setParameter(11, nullIfEmpty(fields[10]));                // token
        query.setParameter(12, nullIfEmpty(fields[11]));                // reference_value
        query.setParameter(13, nullIfEmpty(fields[12]));                // default_upstream_value
        query.setParameter(14, nullIfEmpty(fields[13]));                // override_upstream_value
        query.executeUpdate();
    }

    /**
     * Inserts a new report row. {@code element_key} carried over verbatim (or freshly
     * generated) — see {@link #resolveElementKey(String)}.
     * Fields: source_id|element_key|name|description|url|display_order
     */
    private void insertReport(String[] fields, Long surveyId) {
        if (fields.length < 6) {
            throw new IllegalArgumentException("reports requires 6 fields, got " + fields.length);
        }
        UUID elementKey = resolveElementKey(fields[1]);
        Query query = em.createNativeQuery("""
                INSERT INTO survey.reports (id, survey_id, report_key, name, description, url, display_order)
                VALUES (nextval('survey.reports_seq'), ?1, ?2, ?3, ?4, ?5, ?6)
                """);
        query.setParameter(1, surveyId);
        query.setParameter(2, elementKey);
        query.setParameter(3, nullIfEmpty(fields[2]));
        query.setParameter(4, nullIfEmpty(fields[3]));
        query.setParameter(5, nullIfEmpty(fields[4]));
        query.setParameter(6, parseIntOrNull(fields[5]));
        query.executeUpdate();
    }

    /**
     * Inserts a new post_survey_action row. {@code element_key} carried over verbatim (or
     * freshly generated) — see {@link #resolveElementKey(String)}.
     * Fields: source_id|element_key|name|description|url|execution_order
     */
    private void insertPostSurveyAction(String[] fields, Long surveyId) {
        if (fields.length < 6) {
            throw new IllegalArgumentException("post_survey_actions requires 6 fields, got " + fields.length);
        }
        UUID elementKey = resolveElementKey(fields[1]);
        Query query = em.createNativeQuery("""
                INSERT INTO survey.post_survey_actions
                    (id, survey_id, post_survey_action_key, name, description, url, execution_order)
                VALUES (nextval('survey.post_survey_actions_seq'), ?1, ?2, ?3, ?4, ?5, ?6)
                """);
        query.setParameter(1, surveyId);
        query.setParameter(2, elementKey);
        query.setParameter(3, nullIfEmpty(fields[2]));
        query.setParameter(4, nullIfEmpty(fields[3]));
        query.setParameter(5, nullIfEmpty(fields[4]));
        query.setParameter(6, parseIntOrNull(fields[5]));
        query.executeUpdate();
    }

    /**
     * Inserts a new dimension row, or reuses an existing row if name already exists — dimensions
     * are a shared, global lookup (not survey-scoped), so reuse takes priority over the file's
     * own {@code element_key} when a same-named row is already present in this instance.
     * Fields: source_id|element_key|name
     *
     * @return the new or existing dimension ID
     */
    private Long insertOrReuseDimension(String[] fields) {
        if (fields.length < 3) {
            throw new IllegalArgumentException("dimensions requires 3 fields, got " + fields.length);
        }
        String name = nullIfEmpty(fields[2]);

        // Check for existing dimension by name (unique constraint)
        Query existQuery = em.createNativeQuery(
                "SELECT id FROM survey.dimensions WHERE name = ?1");
        existQuery.setParameter(1, name);
        Long existingId = getLongResult(existQuery);
        if (existingId != null) {
            return existingId;
        }

        UUID elementKey = resolveElementKey(fields[1]);
        Query seqQuery = em.createNativeQuery("SELECT nextval('survey.dimensions_seq')");
        Long newId = ((Number) seqQuery.getSingleResult()).longValue();

        Query query = em.createNativeQuery("""
                INSERT INTO survey.dimensions (id, dimension_key, name)
                VALUES (?1, ?2, ?3)
                """);
        query.setParameter(1, newId);
        query.setParameter(2, elementKey);
        query.setParameter(3, name);
        query.executeUpdate();
        return newId;
    }

    /**
     * Inserts a new ontology row, or reuses an existing row if (name, tag) already exists
     * in the target system (since the unique constraint covers only those two columns).
     * Fields: source_id|element_key|name|tag|dimension
     *
     * @param dimensionIdMap mapping of old dimension IDs to new/existing dimension IDs
     * @return the new or existing ontology ID that should be used when resolving ontology_id references
     */
    private Long insertOrReuseOntology(String[] fields, Long surveyId, Map<Long, Long> dimensionIdMap) {
        if (fields.length < 5) {
            throw new IllegalArgumentException("ontology requires 5 fields, got " + fields.length);
        }
        String name = nullIfEmpty(fields[2]);
        String tag = nullIfEmpty(fields[3]);

        // Check for existing (name, tag) pair — unique constraint is only on these two columns
        Query existQuery = em.createNativeQuery(
                "SELECT id FROM survey.ontology WHERE name = ?1 AND tag = ?2");
        existQuery.setParameter(1, name);
        existQuery.setParameter(2, tag);
        Long existingId = getLongResult(existQuery);
        if (existingId != null) {
            return existingId;
        }

        UUID elementKey = resolveElementKey(fields[1]);
        // Resolve dimension ID via map (nullable)
        Long oldDimensionId = parseLongOrNull(fields[4]);
        Long newDimensionId = resolveNullable(oldDimensionId, dimensionIdMap, "dimension (ontology)");

        Query seqQuery = em.createNativeQuery("SELECT nextval('survey.ontology_seq')");
        Long newId = ((Number) seqQuery.getSingleResult()).longValue();

        Query query = em.createNativeQuery("""
                INSERT INTO survey.ontology (id, survey_id, ontology_key, name, tag, dimension)
                VALUES (?1, ?2, ?3, ?4, ?5, ?6)
                """);
        query.setParameter(1, newId);
        query.setParameter(2, surveyId);
        query.setParameter(3, elementKey);
        query.setParameter(4, name);
        query.setParameter(5, tag);
        query.setParameter(6, newDimensionId);
        query.executeUpdate();
        return newId;
    }

    /**
     * Inserts a new metadata row; the 3 FK-ish columns (durable) resolved via maps. metadata
     * itself is not Type 2 versioned — its own {@code id} is a plain nextval, no map needed.
     * {@code element_key} carried over verbatim (or freshly generated) — see
     * {@link #resolveElementKey(String)}.
     * Fields: source_id|element_key|steps_sections_id|question_id|sections_question_id|ontology_id|value
     */
    private void insertMetadata(String[] fields, Long surveyId,
            Map<Long, Long> stepsSectionIdMap, Map<Long, Long> questionIdMap,
            Map<Long, Long> sectionsQuestionIdMap, Map<Long, Long> ontologyIdMap) {
        if (fields.length < 7) {
            throw new IllegalArgumentException("metadata requires 7 fields, got " + fields.length);
        }
        UUID elementKey = resolveElementKey(fields[1]);
        Long newStepsSectionsId = resolveNullable(parseLongOrNull(fields[2]), stepsSectionIdMap, "steps_section (metadata)");
        Long newQuestionId = resolveNullable(parseLongOrNull(fields[3]), questionIdMap, "question (metadata)");
        Long newSectionsQuestionId = resolveNullable(parseLongOrNull(fields[4]), sectionsQuestionIdMap, "sections_question (metadata)");
        Long newOntologyId = resolveRequired(parseLongOrNull(fields[5]), ontologyIdMap, "ontology (metadata)");

        Query query = em.createNativeQuery("""
                INSERT INTO survey.metadata
                    (id, survey_id, metadata_key, steps_sections_id, question_id, sections_question_id, ontology_id, value)
                VALUES (nextval('survey.metadata_seq'), ?1, ?2, ?3, ?4, ?5, ?6, ?7)
                """);
        query.setParameter(1, surveyId);
        query.setParameter(2, elementKey);
        query.setParameter(3, newStepsSectionsId);
        query.setParameter(4, newQuestionId);
        query.setParameter(5, newSectionsQuestionId);
        query.setParameter(6, newOntologyId);
        query.setParameter(7, nullIfEmpty(fields[6]));
        query.executeUpdate();
    }

    // -------------------------------------------------------------------------
    // Parser / ID-resolution helpers — shared with SurveyDefinitionUpdateService,
    // see SurveyDefinitionFileFields.
    // -------------------------------------------------------------------------

    private String[] parseFields(String data) {
        return SurveyDefinitionFileFields.parseFields(data);
    }

    private Long resolveRequired(Long oldId, Map<Long, Long> map, String entityDesc) {
        return SurveyDefinitionFileFields.resolveRequired(oldId, map, entityDesc);
    }

    private Long resolveNullable(Long oldId, Map<Long, Long> map, String entityDesc) {
        return SurveyDefinitionFileFields.resolveNullable(oldId, map, entityDesc);
    }

    private String nullIfEmpty(String value) {
        return SurveyDefinitionFileFields.nullIfEmpty(value);
    }

    private Integer parseIntOrNull(String value) {
        return SurveyDefinitionFileFields.parseIntOrNull(value);
    }

    private Long parseLongOrNull(String value) {
        return SurveyDefinitionFileFields.parseLongOrNull(value);
    }

    private boolean parseBooleanOrFalse(String value) {
        return SurveyDefinitionFileFields.parseBooleanOrFalse(value);
    }

    private Long getDurableId(String durableColumn, String table, Long surrogateId) {
        return SurveyDefinitionFileFields.getDurableId(em, durableColumn, table, surrogateId);
    }

    private Long getLongResult(Query query) {
        return SurveyDefinitionFileFields.getLongResult(query);
    }
}
