#!/usr/bin/env bash
#
# Builds the administrator's manual (UC-029) and drops the PDF where the application packages it.
#
# The manual is typeset by a TeX Live container, so no TeX installation is needed on the
# machine doing the build. The version and build date are stamped into the document
# (UC-029 BR-003); when they are not supplied both read "unknown" (UC-029 A3).
#
# Usage: docs/manual/build-manual.sh [version] [build-date]
#
# Env:
#   TEXLIVE_IMAGE   container image to typeset with (default texlive/texlive:latest)
#   MANUAL_OUT      where to write the PDF (default src/main/resources/manual)
#   SKIP_MANUAL=1   skip the build entirely and exit 0

set -euo pipefail

MANUAL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "${MANUAL_DIR}/../.." && pwd)"

TEXLIVE_IMAGE="${TEXLIVE_IMAGE:-texlive/texlive:latest}"
MANUAL_OUT="${MANUAL_OUT:-${PROJECT_DIR}/src/main/resources/manual}"
JOB="elicit-admin-manual"
PDF_NAME="elicit-admin-manual.pdf"

if [[ "${SKIP_MANUAL:-0}" == "1" ]]; then
  echo "[manual] SKIP_MANUAL=1 — not building the manual"
  exit 0
fi

# The version and build date the PDF is stamped with. Default to the pom's version and today,
# so a hand-run build still produces an attributable document.
VERSION="${1:-}"
BUILD_DATE="${2:-}"
if [[ -z "${VERSION}" ]]; then
  VERSION="$(sed -n '1,20p' "${PROJECT_DIR}/pom.xml" | grep -m1 -o '<version>[^<]*</version>' | sed 's/<[^>]*>//g' || true)"
fi
VERSION="${VERSION:-unknown}"
BUILD_DATE="${BUILD_DATE:-$(date -u '+%Y-%m-%d %H:%M:%S UTC')}"

if ! command -v docker >/dev/null 2>&1; then
  echo "[manual] docker is not available — cannot typeset the manual." >&2
  echo "[manual] Install Docker, or set SKIP_MANUAL=1 to build the application without it." >&2
  exit 1
fi

echo "[manual] version ${VERSION}, built ${BUILD_DATE}"

# LaTeX takes the stamp from a generated file rather than the command line, so the same
# sources build by hand (with "unknown") and in the application build (with the real values).
cat > "${MANUAL_DIR}/build-info.tex" <<EOF
%% Generated by docs/manual/build-manual.sh — do not edit, do not commit.
\\newcommand{\\elicitVersion}{${VERSION}}
\\newcommand{\\elicitBuildDate}{${BUILD_DATE}}
EOF

echo "[manual] typesetting with ${TEXLIVE_IMAGE}"
docker run --rm \
  -v "${MANUAL_DIR}:/manual" \
  -w /manual \
  -u "$(id -u):$(id -g)" \
  -e HOME=/tmp \
  "${TEXLIVE_IMAGE}" \
  latexmk -lualatex -interaction=nonstopmode -halt-on-error -file-line-error \
          -outdir=build "${JOB}.tex"

mkdir -p "${MANUAL_OUT}"
cp "${MANUAL_DIR}/build/${JOB}.pdf" "${MANUAL_OUT}/${PDF_NAME}"

echo "[manual] wrote ${MANUAL_OUT}/${PDF_NAME} ($(du -h "${MANUAL_OUT}/${PDF_NAME}" | cut -f1))"
