package com.elicitsoftware.rest;

/*-
 * ***LICENSE_START***
 * Elicit Survey
 * %%
 * Copyright (C) 2025 - 2026 The Regents of the University of Michigan - Rogel Cancer Center
 * %%
 * PolyForm Noncommercial License 1.0.0
 * <https://polyformproject.org/licenses/noncommercial/1.0.0>
 * ***LICENSE_END***
 */

import com.elicitsoftware.admin.upload.MultipartBody;
import com.elicitsoftware.service.SurveyDefinitionUpdateService;
import io.quarkus.logging.Log;
import jakarta.annotation.security.RolesAllowed;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;

import java.util.Map;
import java.util.UUID;

/**
 * REST endpoint that applies a survey definition file to an existing survey in place — UC-017
 * (Update Survey Definition), the counterpart to {@link SurveyDefinitionImportResource} (UC-014,
 * which always creates a brand-new survey).
 *
 * @see SurveyDefinitionUpdateService
 */
@Path("/secured/survey/update")
@ApplicationScoped
public class SurveyDefinitionUpdateResource {

    /**
     * Default constructor for CDI.
     */
    public SurveyDefinitionUpdateResource() {
        // CDI managed bean
    }

    @Inject
    SurveyDefinitionUpdateService surveyDefinitionUpdateService;

    /**
     * Applies a survey definition file to the survey identified by {@code multipartBody.surveyId}.
     * <p>
     * The file should be one generated by the survey export endpoint (.elicit format). The
     * file's stable {@code survey_key} must match the target survey's own key (BR-063); on a
     * mismatch, or a missing key, no changes are made.
     *
     * @param multipartBody multipart form data: the file in the "file" field, target survey id
     *     in the "surveyId" field
     * @return JSON response with per-table created/versioned/unchanged counts or error information
     */
    @POST
    @RolesAllowed("elicit_admin")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @Produces(MediaType.APPLICATION_JSON)
    public Response updateSurvey(MultipartBody multipartBody) {
        if (multipartBody.file == null) {
            return Response.status(Response.Status.BAD_REQUEST)
                    .entity(new UpdateResponse(false, "No file provided in the 'file' field", null))
                    .build();
        }

        Integer targetSurveyId = parseSurveyId(multipartBody.surveyId);
        if (targetSurveyId == null) {
            return Response.status(Response.Status.BAD_REQUEST)
                    .entity(new UpdateResponse(false, "No target survey selected in the 'surveyId' field", null))
                    .build();
        }

        try {
            SurveyDefinitionUpdateService.UpdateResult result =
                    surveyDefinitionUpdateService.updateFromFile(multipartBody.file, multipartBody.fileName, targetSurveyId);

            UpdateResponse response = new UpdateResponse(
                    result.isSuccess(),
                    result.isSuccess() ? "Update completed successfully"
                            : String.join("; ", result.getErrors()),
                    result.getCounts()
            );

            if (result.isSuccess()) {
                return Response.ok(response).build();
            } else {
                boolean notFound = result.getErrors().stream().anyMatch(e -> e.contains("Target survey not found"));
                Response.Status status = notFound ? Response.Status.NOT_FOUND : Response.Status.BAD_REQUEST;
                return Response.status(status).entity(response).build();
            }

        } catch (Exception e) {
            String correlationId = UUID.randomUUID().toString();
            Log.errorf(e, "Survey definition update failed [correlationId=%s]", correlationId);
            UpdateResponse response = new UpdateResponse(false,
                    "Update failed due to an unexpected error. Reference: " + correlationId, null);
            return Response.status(Response.Status.INTERNAL_SERVER_ERROR)
                    .entity(response)
                    .build();
        }
    }

    /**
     * Parses the multipart {@code surveyId} form field (a String per Quarkus issue #8239) to an
     * Integer, returning {@code null} for absent or unparseable input rather than throwing.
     */
    private Integer parseSurveyId(String rawSurveyId) {
        if (rawSurveyId == null || rawSurveyId.isBlank()) {
            return null;
        }
        try {
            return Integer.parseInt(rawSurveyId.trim());
        } catch (NumberFormatException e) {
            return null;
        }
    }

    /**
     * Response DTO for survey definition update operations.
     */
    public static class UpdateResponse {
        private boolean success;
        private String message;
        private Map<String, SurveyDefinitionUpdateService.TableUpdateCounts> counts;

        /**
         * Default constructor for JSON serialization.
         */
        public UpdateResponse() {
        }

        /**
         * Creates a new UpdateResponse.
         *
         * @param success whether the update succeeded
         * @param message status or error message
         * @param counts per-table created/versioned/unchanged breakdown
         */
        public UpdateResponse(boolean success, String message,
                Map<String, SurveyDefinitionUpdateService.TableUpdateCounts> counts) {
            this.success = success;
            this.message = message;
            this.counts = counts;
        }

        /** @return whether the update succeeded */
        public boolean isSuccess() { return success; }

        /** @param success whether the update succeeded */
        public void setSuccess(boolean success) { this.success = success; }

        /** @return status or error message */
        public String getMessage() { return message; }

        /** @param message status or error message */
        public void setMessage(String message) { this.message = message; }

        /** @return per-table created/versioned/unchanged breakdown */
        public Map<String, SurveyDefinitionUpdateService.TableUpdateCounts> getCounts() { return counts; }

        /** @param counts per-table created/versioned/unchanged breakdown */
        public void setCounts(Map<String, SurveyDefinitionUpdateService.TableUpdateCounts> counts) { this.counts = counts; }
    }
}
