GRANT ALL ON SEQUENCE surveyadmin.surveys_seq TO ${surveyadmin_user};
GRANT DELETE, INSERT, SELECT, UPDATE ON surveyadmin.surveys TO ${surveyadmin_user};
GRANT ALL ON SEQUENCE surveyadmin.reports_seq TO ${surveyadmin_user};
GRANT DELETE, INSERT, SELECT, UPDATE ON surveyadmin.reports TO ${surveyadmin_user};
GRANT ALL ON SEQUENCE surveyadmin.message_types_seq TO ${surveyadmin_user};
GRANT DELETE, INSERT, SELECT, UPDATE ON surveyadmin.message_types TO ${surveyadmin_user};
GRANT ALL ON SEQUENCE surveyadmin.departments_seq TO ${surveyadmin_user};
GRANT DELETE, INSERT, SELECT, UPDATE ON surveyadmin.departments TO ${surveyadmin_user};
GRANT ALL ON SEQUENCE surveyadmin.respondents_seq TO ${surveyadmin_user};
GRANT DELETE, INSERT, SELECT, UPDATE ON surveyadmin.respondents TO ${surveyadmin_user};
GRANT ALL ON SEQUENCE surveyadmin.users_seq TO ${surveyadmin_user};
GRANT DELETE, INSERT, SELECT, UPDATE ON surveyadmin.users TO ${surveyadmin_user};
GRANT DELETE, INSERT, SELECT, UPDATE ON surveyadmin.user_surveys TO ${surveyadmin_user};
GRANT ALL ON SEQUENCE surveyadmin.roles_seq TO ${surveyadmin_user};
GRANT DELETE, INSERT, SELECT, UPDATE ON surveyadmin.roles TO ${surveyadmin_user};
GRANT DELETE, INSERT, SELECT, UPDATE ON surveyadmin.user_roles TO ${surveyadmin_user};
GRANT DELETE, INSERT, SELECT, UPDATE ON surveyadmin.user_departments TO ${surveyadmin_user};
GRANT ALL ON SEQUENCE surveyadmin.message_templates_seq TO ${surveyadmin_user};
GRANT DELETE, INSERT, SELECT, UPDATE ON surveyadmin.message_templates TO ${surveyadmin_user};
GRANT ALL ON SEQUENCE surveyadmin.messages_seq TO ${surveyadmin_user};
GRANT DELETE, INSERT, SELECT, UPDATE ON surveyadmin.messages TO ${surveyadmin_user};
